### ISSUE TITLE
Navbar 

### ISSUE THREAD

**Issue by SamikshaSankar** [rockingrohit9639/project-zone#10]
Sticky Navbar &  changes style of login button

please assign @rockingrohit9639

**Comment by Hardikpoudel** [comment]
So we need to make navbar sticky at the top even after scrolling the page?
I'ld like to perform the task

**Comment by rockingrohit9639** [comment]
> So we need to make navbar sticky at the top even after scrolling the page?
> I'ld like to perform the task

@Hardikpoudel  bro, this issue is created by another participant. She has right on it. 
You can comment on issues created by me or you can create new ones.

**Comment by RiyaGupta89** [comment]
May I work on this issue and make the navbar sticky?

**Comment by rockingrohit9639** [comment]
@SamikshaSankar you are given 3 days to complete both issues.
