### ISSUE TITLE
fix dark mode

### ISSUE THREAD

**Issue by satyampgt4** [rockingrohit9639/project-zone#105]
## Describe the bug/feature

Dark mode is  not working properly

## To Reproduce

1. Toggle the dark mode button

## Screenshots

![image](https://user-images.githubusercontent.com/59261812/122748816-3fb48300-d2aa-11eb-8acd-37186700b272.png)
![image](https://user-images.githubusercontent.com/59261812/122748836-4511cd80-d2aa-11eb-809d-f1cad6be2545.png)
----------------------------------
------------------------------------
![image](https://user-images.githubusercontent.com/59261812/122748917-5a86f780-d2aa-11eb-8721-e4351fb8436e.png)
![image](https://user-images.githubusercontent.com/59261812/122748984-6c689a80-d2aa-11eb-8536-04f5f200bf5f.png)

**Comment by rockingrohit9639** [comment]
Hey @satyampgt4, I know this bug, I was planning you fix this once the frontend is ready. Otherwise, we have to change it whenever we add something new.

**Comment by satyampgt4** [comment]
Okay
