### ISSUE TITLE
Connect Frontend with backend for Login and Signup

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#107]
Connect the frontend and the backend in project.

**Comment by naveen8801** [comment]
@rockingrohit9639 I'd like to work on it, please assign :)

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 I'd like to work on it, please assign :)

You can start working on it. You are given 6 days to complete it.

**Comment by naveen8801** [comment]
hi @rockingrohit9639 @kanak22 , should i hold this issue for sometime cause login & signup page are being redesigned ?

**Comment by rockingrohit9639** [comment]
> hi @rockingrohit9639 @kanak22 , should i hold this issue for sometime cause login & signup page are being redesigned ?

Now, you can continue working. The login page is ready now.
