### ISSUE TITLE
Separate search bar from homepage

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#108]
Create a separate page and show the SearchBar there and only fetch the project when the user clicks on the search button.

**Comment by Shaishav0507** [comment]
Can I work on this ?

**Comment by satyampgt4** [comment]
> Can I work on this ?

you can start working on it, make sure to complete this within 6 days

**Comment by rockingrohit9639** [comment]
Hey, @Shaishav0507 are you working on this issue?

**Comment by Shaishav0507** [comment]
@rockingrohit9639 Yes I'm working.
Recently I got vaccinated, so I was down for 2-3 days

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 Yes I'm working.
> Recently I got vaccinated, so I was down for 2-3 days

Ohhh okay, No problem. Take care brother.

**Comment by Shaishav0507** [comment]
@rockingrohit9639 Thank you.
Will send you within 1-2 days

**Comment by rockingrohit9639** [comment]
hey @Shaishav0507 bro I am unassigning you from this issue as there is no response from your side
