### ISSUE TITLE
Redesign and Improve Login page

### ISSUE THREAD

**Issue by kanak22** [rockingrohit9639/project-zone#111]
Redesign and improve the login page.

**Comment by ShwetKhatri2001** [comment]
I would like to work on this issue

**Comment by kanak22** [comment]
@ShwetKhatri2001 Go Ahead :) you have 6 days to complete it

**Comment by rockingrohit9639** [comment]
Hey @ShwetKhatri2001 I have prepared a design for the Login page, It would be great if you can do something similar 🔽 

![image](https://user-images.githubusercontent.com/40729749/122863669-d6338380-d340-11eb-8848-a1c81d92020a.png)

You can contact me for the images
