### ISSUE TITLE
Redesign and Improve Signup page

### ISSUE THREAD

**Issue by kanak22** [rockingrohit9639/project-zone#112]
Redesign and Improve Signup page.

**Comment by ShwetKhatri2001** [comment]
@kanak22 @rockingrohit9639 I would like to work on this issue

**Comment by anushruti11** [comment]
@rockingrohit9639 I would like to work on this issue.

**Comment by kanak22** [comment]
@ShwetKhatri2001 since u are working on login page .. so let @anushruti11 work on this :)

**Comment by kanak22** [comment]
@anushruti11 you have 6 days to complete it

**Comment by rockingrohit9639** [comment]
Hey, @anushruti11 I have created a design for the Signup page. It would be great if you can do something similar to this 🔽 

![image](https://user-images.githubusercontent.com/40729749/122864010-7689a800-d341-11eb-89f1-f5d8e12f2eda.png)


You can contact me for the images
