### ISSUE TITLE
Read more not visible in dark mode

### ISSUE THREAD

**Issue by supzi-del** [rockingrohit9639/project-zone#115]
## Describe the bug/feature

The read more link is black in colour, when the dark mode is toggled, it is not clearly visible.

## To Reproduce

1. Changing the colour of read more link when dark mode is toggled.
2.
3.
4.

## Logs

If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):

- OS: Windows
- Browser: Chrome

## Additional context

![Screenshot (270)](https://user-images.githubusercontent.com/78655439/122980861-cb1b3a80-d3b6-11eb-97f9-b93e7784fb65.png)

**Comment by supzi-del** [comment]
I would like to work on it under LGMSOC.

**Comment by rockingrohit9639** [comment]
Hii @supzi-del we are holding to work on dark mode for now. When the frontend work will be almost done then we will update dark mode.
