### ISSUE TITLE
On contact form submission user is sent to fresh new page with a successful message being displayed 

### ISSUE THREAD

**Issue by ROHAN842** [rockingrohit9639/project-zone#117]
## Describe the bug/feature

As when user fills all the detail and clicks on "Send" button in Contact us section then site doesn't take any response and the user doesn't get any confirmation that whether the message is sent successfully or not!

## Expected behavior

I want to add a feature without back end with which user would be sent to a fresh new page on clicking Send button where the message will be written, lets say "Thank you for your submission , Return back ".

## Additional context

![image](https://user-images.githubusercontent.com/61961107/123112205-2868c780-d45b-11eb-913c-12e0ce07b1af.png)

Can I work on this issue?

Please assign this issue to me under LGMSOC

**Comment by rockingrohit9639** [comment]
Hey, @ROHAN842 you can start working on this. You are given 5 days to complete this.
