### ISSUE TITLE
Add comment section in ProjectDetailsCard component

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#123]
Add a comment section in ProjectDetailsCard component like below ⬇️ 

![image](https://user-images.githubusercontent.com/40729749/123223836-dbcecc00-d4ee-11eb-9310-b67bfbbf1588.png)

**Comment by anushruti11** [comment]
I would like to work on this issue

**Comment by satyampgt4** [comment]
you can start working on this issue now. Make sure you complete this issue in 5 days.
