### ISSUE TITLE
Make explore categories responsive

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#125]
Make explore categories 🔽  section responsive. 

![image](https://user-images.githubusercontent.com/40729749/123368934-5b65a500-d59a-11eb-852a-b2b18ca3b0b6.png)
 
It should be mobile responsive.

**Comment by ShwetKhatri2001** [comment]
I would like to work on this issue, I am going to complete my previously assigned issue soon

**Comment by rockingrohit9639** [comment]
> I would like to work on this issue, I am going to complete my previously assigned issue soon

Okay, I will assign you once you complete the other one.

**Comment by rockingrohit9639** [comment]
hey @ShwetKhatri2001 You can start working on this issue. You are given 4 days to complete it.
