### ISSUE TITLE
Create dashboard page

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#126]
Create a dashboard component something like 👇 

![image](https://user-images.githubusercontent.com/40729749/123375425-61618300-d5a6-11eb-91dc-4007f7c75837.png)

Badges are optional for now. But you can create it if you want.
Route (render component) - /profile

**Comment by ShwetKhatri2001** [comment]
I would like to work on this issue

**Comment by rockingrohit9639** [comment]
> I would like to work on this issue

You can start working on this issue. You are given 6 days to complete this.
