### ISSUE TITLE
Want to add Particle Background Animation 

### ISSUE THREAD

**Issue by ROHAN842** [rockingrohit9639/project-zone#128]
## Describe the feature

I want to add particle background animation in different pages of the website.

Some examples of how website will look after adding it to background are as :-

![image](https://user-images.githubusercontent.com/61961107/123441528-95ae6100-d5f1-11eb-8f8f-0491c9aa2db9.png)

![image](https://user-images.githubusercontent.com/61961107/123441598-a8c13100-d5f1-11eb-9b67-d629d8cc3b93.png)

![image](https://user-images.githubusercontent.com/61961107/123441721-cbebe080-d5f1-11eb-816d-3eb5e0bb205a.png)

![image](https://user-images.githubusercontent.com/61961107/123441800-df974700-d5f1-11eb-859c-c44d74292e7f.png)

![image](https://user-images.githubusercontent.com/61961107/123441881-f5a50780-d5f1-11eb-8591-d05dd69c8028.png)

**Comment by kanak22** [comment]
Go Ahead @ROHAN842 :)

**Comment by ROHAN842** [comment]
Hey @kanak22 kindly attach  the LGMSOC and Level(whichever) to this issue

**Comment by kanak22** [comment]
Sure
