### ISSUE TITLE
Dark Mode Toggle 

### ISSUE THREAD

**Issue by Rutuj-Runwal** [rockingrohit9639/project-zone#13]
- Adding a Dark-Mode toggle switch to the site

**Comment by Rutuj-Runwal** [comment]
Please assign @rockingrohit9639 
This Issue is a part of my contribution towards LGM-SOC'21

**Comment by rockingrohit9639** [comment]
> Please assign @rockingrohit9639
> This Issue is a part of my contribution towards LGM-SOC'21

I have assigned you this issue. Make sure you complete it in 6 days.
