### ISSUE TITLE
Adding Loader during starting of application

### ISSUE THREAD

**Issue by naveen8801** [rockingrohit9639/project-zone#130]
## Describe the bug/feature

Add a loader when the application starts during that time app will check whether any user has logged in or not. loader will be added in App.js in useEffect where profile data is being fetched. Loader can be of any form for example an overlay display with full width and height having a spinner.

## Additional context
@kanak22 @rockingrohit9639 please add the 'good first issue' label to it.

**Comment by mayankmohak** [comment]
can i work on this issue.

**Comment by rockingrohit9639** [comment]
> can i work on this issue.

You can start working on this issue. You are given 3 days to complete this.

**Comment by rockingrohit9639** [comment]
hey @mayankmohak bro, are you working on it?

**Comment by mayankmohak** [comment]
sry i actually missed the notification.
I will be doing in couple of hours.

**Comment by rockingrohit9639** [comment]
> h

okay

**Comment by mayankmohak** [comment]
made a pr please review.
