### ISSUE TITLE
Restrict /addnew route to authenticated users only

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#131]
## Describe the bug/feature

For now, an unauthenticated user can access /addnew page by typing the route in the URL. This should not happen. So, restrict this route to authenticated users only.
This means that if the user is authenticated then only they can access this page otherwise navigate them to the homepage.

**Comment by VenomFate-619** [comment]
can do this

**Comment by rockingrohit9639** [comment]
> can do this

ok, you can start working on it. You are given 4 days to complete it.
Help - 
- We have a state in ContextAPI that holds that the user is authenticated or not. You can use that on this page.

**Comment by VenomFate-619** [comment]
Can I make a Private route wrapper and if yes then what should be the folder 📁 name

**Comment by rockingrohit9639** [comment]
> Can I make a Private route wrapper and if yes then what should be the folder 📁 name

why would you do that?

**Comment by VenomFate-619** [comment]
So, that we can have a logic for all private routes at one place

**Comment by rockingrohit9639** [comment]
> So, that we can have a logic for all private routes at one place

You don't need anything on the server. You can do is using a state variable called isAuthenticated.
