### ISSUE TITLE
Add loading indicator on login and signup page

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#132]
After filling out the signup or login form, when we click on the Signup/Login button the form gets reset and nothing happens for some seconds. And after some seconds we saw the message that the user is signed up or not.

So, add a loading indicator that runs when the user clicks on the signup button and when the message appears, it should be hidden.

**Comment by abhishekkumar08** [comment]
Can I work on this??

**Comment by rockingrohit9639** [comment]
> Can I work on this??

Yes, go ahead, you are given 4 days to complete this.

**Comment by kanak22** [comment]
Hey @abhishekkumar08 any updates?

**Comment by abhishekkumar08** [comment]
> Hey @abhishekkumar08 any updates? 

I'm sorry, busy in my college exams. You can unassign me.

**Comment by kanak22** [comment]
Okay no problem :)
