### ISSUE TITLE
Redesign Add New Project page

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#133]
Redesign Add New Project page similar to the image below 👇 

![image](https://user-images.githubusercontent.com/40729749/123503911-a0a9d580-d673-11eb-87f4-2e8cdabc5a6e.png)

You can contact me for images and other resources.

**Comment by RiyaGupta89** [comment]
I can do this. Please assign me this issue.

**Comment by satyampgt4** [comment]
> I can do this. Please assign me this issue.

You can start working on this issue, make sure to complete this within 6 days

**Comment by rockingrohit9639** [comment]
> > I can do this. Please assign me this issue.
> 
> You can start working on this issue, make sure to complete this within 6 days

@satyampgt4 She is already assigned to another issue. Please look for the other issues too. We cannot assign a single person to multiple issues at the same time.

**Comment by satyampgt4** [comment]
> > > I can do this. Please assign me this issue.
> > 
> > 
> > You can start working on this issue, make sure to complete this within 6 days
> 
> @satyampgt4 She is already assigned to another issue. Please look for the other issues too. We cannot assign a single person to multiple issues at the same time.

I had read the conversation of that issue so I thought problem regarding API has been solved

>We cannot assign a single person to multiple issues at the same time.

### I will take care of this in future

**Comment by RiyaGupta89** [comment]
Now can I work on this issue? From where will I get that purple plane image?

**Comment by rockingrohit9639** [comment]
> Now can I work on this issue? From where will I get that purple plane image?

Ping me on Discord or Slack. I will send you that image.

**Comment by RiyaGupta89** [comment]
@rockingrohit9639 I did this much . I don't know why project level textfield and language textfield are not even clickable. Also nothing major changes when i tried adding styling to it. Can i remove material ui fields and use html tags to add the field and styling? But the functionality will be gone then.
![newproject](https://user-images.githubusercontent.com/72425181/123546633-1187e500-d77b-11eb-96f2-5a6a6f6628d0.png)

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 I did this much . I don't know why project level textfield and language textfield are not even clickable. Also nothing major changes when i tried adding styling to it. Can i remove material ui fields and use html tags to add the field and styling? But the functionality will be gone then.
> ![newproject](https://user-images.githubusercontent.com/72425181/123546633-1187e500-d77b-11eb-96f2-5a6a6f6628d0.png)

the right thing you are doing is not to be done this way, these are the dropdown designs which will show as suggestions when user clicks on the input field

**Comment by RiyaGupta89** [comment]
Should I then leave this issue? Because I am not very much familiar with React. I just know the  basics. And this functionality thing seems complex to me, I might mess it up.

**Comment by rockingrohit9639** [comment]
> Should I then leave this issue? Because I am not very much familiar with React. I just know the basics. And this functionality thing seems complex to me, I might mess it up.

Okay, leave it

**Comment by ShwetKhatri2001** [comment]
I would like to work on this issue whenever its possible

**Comment by rockingrohit9639** [comment]
> I would like to work on this issue whenever its possible

Okay bro I will assign you when you completes the other one

**Comment by rockingrohit9639** [comment]
Hi @ShwetKhatri2001 bro, you can start working on this issue. You are given 6 days to complete it.
