### ISSUE TITLE
Add like button and text on Project card

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#134]
Add a like button and text on the Project card like 👇 

![image](https://user-images.githubusercontent.com/40729749/123504188-617c8400-d675-11eb-97bd-017169b69363.png)

**Comment by RiyaGupta89** [comment]
The user should be able to click on that button and like the project too? And the number of likes increases? Is this the task?

**Comment by anushruti11** [comment]
Can I work on this issue?

**Comment by rockingrohit9639** [comment]
> Can I work on this issue?

You can start working on this issue. You are given 3 days to complete this.

**Comment by rockingrohit9639** [comment]
> The user should be able to click on that button and like the project too? And the number of likes increases? Is this the task?

For now, We only need that icon and text there
