### ISSUE TITLE
Integrate User dashboard with server api 

### ISSUE THREAD

**Issue by naveen8801** [rockingrohit9639/project-zone#137]
## Describe the bug/feature

Feature to be added :- 
- User can get his profile data from the database and will be shown on user's dashboard
- Update or upload his/her profile informations including profile pic, badges, bio , description, social links etc.

## Additional context

@rockingrohit9639 @kanak22, please assign, I'd like to work on it :)

**Comment by rockingrohit9639** [comment]
I have assigned you this issue. You are given 6 days to complete it.

**Comment by kanak22** [comment]
go ahead :))
