### ISSUE TITLE
Bug - Make Welcome to dashboard align perfectly with other navbar items

### ISSUE THREAD

**Issue by naveen8801** [rockingrohit9639/project-zone#139]
## Describe the bug/feature

Welcome to dashboard text after sign in or sign up , is not perfectly vertically aligned that's why giving a weird look.

![Screenshot (96)_LI](https://user-images.githubusercontent.com/54985099/123532832-47eb4300-d72e-11eb-84be-24eaf8886940.jpg)

## Expected behavior

All navbar items should be aligned same horizontally and vertically.

## Additional context

@rockingrohit9639 @kanak22, please add label 'good first issue' to it :))

**Comment by RiyaGupta89** [comment]
Can I work on it?

**Comment by kanak22** [comment]
Hey @RiyaGupta89 :) did u completed all the previous issues assigned to you?

**Comment by RiyaGupta89** [comment]
> Hey @RiyaGupta89 :) did u completed all the previous issues assigned to you?

@kanak22  I completed one and for the other one I need the image, when I'll get that image, I'll do that. This issue will not much time so I wanted to work on it.

**Comment by kanak22** [comment]
Okay ;) go ahead  you have 3 days to do this

**Comment by RiyaGupta89** [comment]
![align](https://user-images.githubusercontent.com/72425181/123543555-bfd85e00-d76c-11eb-8f1e-8fb7b1b46106.png)
The alignment is perfectly correct. What do I need to do then?

**Comment by rockingrohit9639** [comment]
> ![align](https://user-images.githubusercontent.com/72425181/123543555-bfd85e00-d76c-11eb-8f1e-8fb7b1b46106.png)
> The alignment is perfectly correct. What do I need to do then?

Make PR

**Comment by rockingrohit9639** [comment]
Hii @RiyaGupta89 have you done it?

**Comment by RiyaGupta89** [comment]
@rockingrohit9639 Yes, I've made a PR.
