### ISSUE TITLE
Changes in "Add New Project"

### ISSUE THREAD

**Issue by Rutuj-Runwal** [rockingrohit9639/project-zone#14]
- [ ] Instead of typing in the "Project Level", Adding in a dropdown to select the Level Eg:"Intermediate"," Beginner" etc....
- [x] Addition of additional non mandatory fields to add links for reference eg: Github Repo , Working Website Demo for appropriate projects

Please Assign @rockingrohit9639 
This Issue is a part of my contribution towards LGM-SOC'21

**Comment by Hardikpoudel** [comment]
I'ld like to work on this issue

**Comment by Rutuj-Runwal** [comment]
@Hardikpoudel Actually I am working on this issue.

**Comment by Hardikpoudel** [comment]
ok i'll choose next one then

**Comment by rockingrohit9639** [comment]
@Hardikpoudel bro, I will assign you this issue when you complete the previous one. And yeah, don't add code of both issues in one PR.

**Comment by rockingrohit9639** [comment]
@Rutuj-Runwal  bro, I will assign you this issue when you complete the previous one. And yeah, don't add the code of both issues in one PR.

**Comment by Rutuj-Runwal** [comment]
@rockingrohit9639 Can I work on this now?

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 Can I work on this now?

Yes @Rutuj-Runwal bro, you can start working on this issue. Dropdown for project level is already added but you can add your second suggestions. You are given 6 days to complete it.

**Comment by rockingrohit9639** [comment]
Hey @Rutuj-Runwal bro, are you working on it?

**Comment by Rutuj-Runwal** [comment]
Yes I am working.....I was unable to push the changes as I was focused on other projects will do it ASAP

> Hey @Rutuj-Runwal bro, are you working on it?

**Comment by rockingrohit9639** [comment]
> Yes I am working.....I was unable to push the changes as I was focused on other projects will do it ASAP
> 
> > Hey @Rutuj-Runwal bro, are you working on it?

Okay, no problem

**Comment by rockingrohit9639** [comment]
Hey, @Rutuj-Runwal I have fixed that issue, now you can word on it. For now, you can just change the frontend we can change the backend later.

**Comment by kanak22** [comment]
@Rutuj-Runwal any updates?
