### ISSUE TITLE
Create an EditProfile Modal

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#140]
Create a Modal on the Profile page which is popped up when the user clicks on the Edit Profile button.
The modal should look like below 👇 

![image](https://user-images.githubusercontent.com/40729749/123535689-0e710280-d743-11eb-8297-1fa0877b58c9.png)

**Comment by ShwetKhatri2001** [comment]
I would like to work on this issue, I am going to complete my previously assigned issue very soon

**Comment by rockingrohit9639** [comment]
> I would like to work on this issue, I am going to complete my previously assigned issue very soon

Okay I will assign you once you complete the other one

**Comment by ShwetKhatri2001** [comment]
You can assign this issue now

**Comment by rockingrohit9639** [comment]
> You can assign this issue now

You can start working on this. You are given 6 days to complete it.
