### ISSUE TITLE
Documentation - Add steps to run server locally & Update images

### ISSUE THREAD

**Issue by naveen8801** [rockingrohit9639/project-zone#145]
## Describe the change

I'd like to edit the readme.md :-
- Add steps to run our server locally 
- Update preview images

## Additional context

@rockingrohit9639 @kanak22, my current issue #137 is on hold that's why I'd like to work on it please assign :-)

**Comment by rockingrohit9639** [comment]
> ## Describe the change
> I'd like to edit the readme.md :-
> 
> * Add steps to run our server locally
> * Update preview images
> 
> ## Additional context
> @rockingrohit9639 @kanak22, my current issue #137 is on hold that's why I'd like to work on it please assign :-)

You can start working on this issue. you are given 3 days to complete it.
