### ISSUE TITLE
Home, Find Projects and About section links are not working in the Footer section

### ISSUE THREAD

**Issue by ROHAN842** [rockingrohit9639/project-zone#146]
## Describe the bug/feature

In the footer section Login/Signup, Contact Us, Trending Projects links are working fine but the above mentioned 3 links are not working fine as there are not redirected to the correct path.

I would like to work on this issue.

Could you please assign this issue to me under LGMSOC so that I can fix this bug.

## Additional context

![image](https://user-images.githubusercontent.com/61961107/123548149-4008be80-d781-11eb-90a1-f24c37fda6ed.png)

**Comment by rockingrohit9639** [comment]
Hey @ROHAN842 bro, only the Find Projects page is not created yet so it is right. And the only thing that needs to be changed is About. Only change the about route everything is fine. You are given 2 days to do it.

**Comment by ROHAN842** [comment]
@rockingrohit9639 OK
