### ISSUE TITLE
Create PR and Issue templates

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#15]
Create Issue and PR templates for the repo.

**Comment by naveen8801** [comment]
Hii @rockingrohit9639 , I'd like to work on it, can you assign it to me please :)

**Comment by rockingrohit9639** [comment]
> Hii @rockingrohit9639 , I'd like to work on it, can you assign it to me please :)

You can start working on it now. Make sure you complete it in 3 days.

**Comment by naveen8801** [comment]
@rockingrohit9639 I have made a PR, please review it :)

**Comment by rockingrohit9639** [comment]
thank you @naveen8801
