### ISSUE TITLE
add customize scrollbar 

### ISSUE THREAD

**Issue by satyampgt4** [rockingrohit9639/project-zone#150]
## Describe the bug/feature

Add customize scrollbar like this **or any other design or color that suits with project**

![image](https://user-images.githubusercontent.com/59261812/123570542-0cac4b00-d7e6-11eb-8869-843a06d14d17.png)

- Browser: all

**Comment by ROHAN842** [comment]
@satyampgt4 I would like to work on this issue

**Comment by rockingrohit9639** [comment]
> @satyampgt4 I would like to work on this issue

you can start working on this issue. You are given 3 days to complete it.

**Comment by ROHAN842** [comment]
@rockingrohit9639 OK

**Comment by ROHAN842** [comment]
https://user-images.githubusercontent.com/61961107/123656200-5419f200-d84d-11eb-9b67-8e21d070b50f.mp4

@rockingrohit9639 bro is this design of scrollbar fine I have also imported animation in it

**Comment by ROHAN842** [comment]
![image](https://user-images.githubusercontent.com/61961107/123656581-ad822100-d84d-11eb-8ef2-3293488adff3.png)

Have a look at this one also this scrollbar borders are curved

**Comment by rockingrohit9639** [comment]
> ![image](https://user-images.githubusercontent.com/61961107/123656581-ad822100-d84d-11eb-8ef2-3293488adff3.png)
> 
> Have a look at this one also this scrollbar borders are curved

This looks good you can go with it.
