### ISSUE TITLE
improving scroll to top button

### ISSUE THREAD

**Issue by kumarishalini6** [rockingrohit9639/project-zone#154]
## Describe the bug/feature

the button box is too long as compare to arrow 
@rockingrohit9639 can i improve the button

**Comment by satyampgt4** [comment]
@kumarishalini6 you will be assigned to this issue once you complete your previous assigned issue

**Comment by satyampgt4** [comment]
@kumarishalini6 you can start working on this issue now

**Comment by kumarishalini6** [comment]
Ok

**Comment by kumarishalini6** [comment]
Please add level on my previous PR
