### ISSUE TITLE
Login and sign up page is not responsive

### ISSUE THREAD

**Issue by kumarishalini6** [rockingrohit9639/project-zone#158]
## Describe the bug/feature
The login and sign up page is not responsive 

@rockingrohit9639 can i work on this issue

**Comment by satyampgt4** [comment]
you can start working on this issue

**Comment by kumarishalini6** [comment]
I have delete that branch and take latest upstream  login , sign up and forget password need to redesign because only images are visible 

![InkedProject Zone - Personal - Microsoft​ Edge 6_29_2021 08_43_58 PM_LI](https://user-images.githubusercontent.com/69043944/123823575-cddfc900-d8a9-11eb-838b-df67d3bfb8cd.jpg)

**Comment by kumarishalini6** [comment]
This is ss of only login page

**Comment by kumarishalini6** [comment]
Now please tell me what to do 
@rockingrohit9639  ??

**Comment by rockingrohit9639** [comment]
> Now please tell me what to do
> @rockingrohit9639 ??

let me check

**Comment by kumarishalini6** [comment]
> > Now please tell me what to do
> > @rockingrohit9639 ??
> 
> let me check

Ok

**Comment by kumarishalini6** [comment]
Also check the responsive

**Comment by rockingrohit9639** [comment]
@kumarishalini6 I have made the changes. Please pull those changes. And please let me know if there are any other issues.

**Comment by kumarishalini6** [comment]
now only responsive is in need i'll do that

**Comment by rockingrohit9639** [comment]
> now only responsive is in need i'll do that

yes please

**Comment by kumarishalini6** [comment]
I have a lots of time but I don't why there is no effect of changes in input and I have tried to redesign it but the inputs are not visible 
@rockingrohit9639 please check where and what is issue

**Comment by rockingrohit9639** [comment]
> I have a lots of time but I don't why there is no effect of changes in input and I have tried to redesign it but the inputs are not visible
> @rockingrohit9639 please check where and what is issue

Okay, I will check.
