### ISSUE TITLE
About us page is not responsive

### ISSUE THREAD

**Issue by kumarishalini6** [rockingrohit9639/project-zone#161]
## Describe the bug/feature

@rockingrohit9639 The about us page is not responsive 
can i work on this issue

**Comment by rockingrohit9639** [comment]
> ## Describe the bug/feature
> @rockingrohit9639 The about us page is not responsive
> can i work on this issue

Yes, you can work on this issue. You are given 3 days to complete it.

**Comment by kumarishalini6** [comment]
> > ## Describe the bug/feature
> > @rockingrohit9639 The about us page is not responsive
> > can i work on this issue
> 
> Yes, you can work on this issue. You are given 3 days to complete it.

ok
