### ISSUE TITLE
Feature - Implement forget password feature

### ISSUE THREAD

**Issue by naveen8801** [rockingrohit9639/project-zone#166]
## Describe the bug/feature

Currently there is no forget password functionality in application.
- Implementing backend route for the same.
- one time password reset link will be sent to user through email.
- Integrating backend route with frontend.

## Additional context

@kanak22  @rockingrohit9639, I'd like to work on it, please assign 🚀

**Comment by rockingrohit9639** [comment]
@naveen8801 I have assigned you this issue. Make sure you complete it in 6 days
