### ISSUE TITLE
Hover effect on categories cards

### ISSUE THREAD

**Issue by RiyaGupta89** [rockingrohit9639/project-zone#168]
![categories](https://user-images.githubusercontent.com/72425181/123897346-da832080-d980-11eb-8fa0-791d104b62ba.png)
Can I add hover effect on these cards?

**Comment by rockingrohit9639** [comment]
> ![categories](https://user-images.githubusercontent.com/72425181/123897346-da832080-d980-11eb-8fa0-791d104b62ba.png)
> Can I add hover effect on these cards?

it is already there.

**Comment by RiyaGupta89** [comment]
> > ![categories](https://user-images.githubusercontent.com/72425181/123897346-da832080-d980-11eb-8fa0-791d104b62ba.png)
> > Can I add hover effect on these cards?
> 
> it is already there.

Okay
