### ISSUE TITLE
Footer for project zone Website

### ISSUE THREAD

**Issue by mayankmohak** [rockingrohit9639/project-zone#17]
Can I get the issue?

Footer will have name and details of project admin @rockingrohit9639

**Comment by rockingrohit9639** [comment]
> Can I get the issue?
> 
> Footer will have name and details of project admin @rockingrohit9639

It would be great if you create a footer. But instead of adding my details, write - Made with ❤️ by open source contributors.

I have assigned you this issue. Make sure you complete it in 5 days.

**Comment by mayankmohak** [comment]
@rockingrohit9639  have a review i have made changes
