### ISSUE TITLE
Responsive categories card

### ISSUE THREAD

**Issue by kumarishalini6** [rockingrohit9639/project-zone#172]
## Describe the bug/feature

Categories card are not responsive 
@rockingrohit9639  can i work on this issue

**Comment by rockingrohit9639** [comment]
> ## Describe the bug/feature
> Categories card are not responsive
> @rockingrohit9639 can i work on this issue

those are already responsive. you have to scroll to view more cards.

**Comment by kumarishalini6** [comment]
Ok
