### ISSUE TITLE
Create and connect frontend of AddNewProject to backend

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#174]
Steps to follow for this issue - 
- Create a route in the backend to add a new project
- Connect frontend with backend

**Comment by ShwetKhatri2001** [comment]
@rockingrohit9639 I would like to work on this issue

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 I would like to work on this issue

Go ahead, You are given 6 days to fix this issue. 
You can reach out to me for URI and other info
