### ISSUE TITLE
Add loading indicator in ShowProject component

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#175]
Add a loading indicator when the user clicks on the search button and remove it when the results are shown on the screen.

**Comment by Amrutha1101** [comment]
I would like to work on this issue under LGM-SOC

**Comment by satyampgt4** [comment]
> I would like to work on this issue under LGM-SOC

you can start working on it . you have 3 days to do this

**Comment by rockingrohit9639** [comment]
@Amrutha1101 are you working on this issue?

**Comment by Amrutha1101** [comment]
Yes @rockingrohit9639

**Comment by rockingrohit9639** [comment]
> Yes @rockingrohit9639

if you are having any problem you can ping me on discord or slack

**Comment by Amrutha1101** [comment]
I'm finding it difficult to set up the project. I've pinged on discord too
