### ISSUE TITLE
Add a loading indicator on Profile component

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#176]
Show a loading indicator when the data is sent from frontend to backend and hide the indicator when a response has been received by backend.

**Comment by ShwetKhatri2001** [comment]
@rockingrohit9639 I would like to work on this issue

**Comment by Amrutha1101** [comment]
I would like to work on this issue under LGM-SOC

**Comment by codingninja11** [comment]
Can I work on this issue? @rockingrohit9639

**Comment by satyampgt4** [comment]
> I would like to work on this issue under LGM-SOC

@Amrutha1101 you are already assigned to another issue. please complete that first

> Can I work on this issue? @rockingrohit9639

@codingninja11 you can start working on it . you have 3 days to do this

**Comment by satyampgt4** [comment]
@codingninja11 Updates on this?

**Comment by codingninja11** [comment]
> @codingninja11 Updates on this?

Sorry but I won't be able to fix this as my exams have started.Please unassign.
