### ISSUE TITLE
Feature - Add verify your email option

### ISSUE THREAD

**Issue by naveen8801** [rockingrohit9639/project-zone#178]
## Describe the bug/feature

I'd like to add ' Verify your email ' functionality on new signup which involves a mail to registered email having a link to verify user's account then we can send daily updates to users

## Additional context

@rockingrohit9639, please assign, I'd like to work on it :-)

**Comment by rockingrohit9639** [comment]
> ## Describe the bug/feature
> I'd like to add ' Verify your email ' functionality on new signup which involves a mail to registered email having a link to verify user's account then we can send daily updates to users
> 
> ## Additional context
> @rockingrohit9639, please assign, I'd like to work on it :-)

Go ahead, you are given 6 days to fix this issue.
