### ISSUE TITLE
Search projects by hitting enter on Homepage

### ISSUE THREAD

**Issue by Veeresh-Rex** [rockingrohit9639/project-zone#18]
Hey, I am LGM-SOC 21 participant. I want to change in searching on homepage by hitting Enter. 
@rockingrohit9639  please assign me this issue.

**Comment by rockingrohit9639** [comment]
> Hey, I am LGM-SOC 21 participant. I want to change in searching on homepage by hitting Enter.
> @rockingrohit9639 please assign me this issue.

Bro, I think someone has already created an issue for the same. I will let you know if they do not complete that.

**Comment by satyampgt4** [comment]
I think #9 issue for same is closed without any pr
@Veeresh-Rex  are you still interested to work on it ...?

**Comment by Veeresh-Rex** [comment]
> 
> 
> I think #9 issue for same is closed without any pr
> @Veeresh-Rex are you still interested to work on it ...?

Yes, Please assign it to me

**Comment by satyampgt4** [comment]
you can start working on this issue now. Make sure you complete this issue in 5 days.

**Comment by rockingrohit9639** [comment]
@Veeresh-Rex bro make sure you make changes to SearchBox component only and not on homepage. Because  has to be shifted to another page. That's why I was holding this issue.
