### ISSUE TITLE
Store user contact messages and send relevant emails

### ISSUE THREAD

**Issue by ShwetKhatri2001** [rockingrohit9639/project-zone#181]
## Describe the bug/feature

- Storing messages sent by user from contact us page to database's user modal
- Sending 'Thanks for visiting' type email to user.
- Sending email to project admin having user-details ( who contacted ) and message he sent ( user's feedback/ message ).

@rockingrohit9639 @kanak22 , I'd like to work on this issue

**Comment by rockingrohit9639** [comment]
> ## Describe the bug/feature
> * Storing messages sent by user from contact us page to database's user modal
> * Sending 'Thanks for visiting' type email to user.
> * Sending email to project admin having user-details ( who contacted ) and message he sent ( user's feedback/ message ).
> 
> @rockingrohit9639 @kanak22 , I'd like to work on this issue

Go ahead, You are given 6 days to fix this issue.
