### ISSUE TITLE
Adding google-login route on backend and integrating it with frontend

### ISSUE THREAD

**Issue by ShwetKhatri2001** [rockingrohit9639/project-zone#183]
## Describe the bug/feature

A user logging in using google is not being stored in database having some basic details currently. so he is not able to edit his profile , we can't store projects added by him or messages sent by him without storing user with required fields.

@rockingrohit9639 I'd like to work on this issue,

**Comment by rockingrohit9639** [comment]
> ## Describe the bug/feature
> A user logging in using google is not being stored in database having some basic details currently. so he is not able to edit his profile , we can't store projects added by him or messages sent by him without storing user with required fields.
> 
> @rockingrohit9639 I'd like to work on this issue,
Yes, for now, it is done using Magic but I am thinking to use oAuth.
Steps for Login using google only (signup is remaining) - 
- When the user clicks on google it should authenticate using OAuth and fetch all data from the database based on the email id he/she has. 
- Show all the data on the website.

(It would be better if you do signup first.)

**Comment by ShwetKhatri2001** [comment]
signup and login both can be handled on a single route onclick to any Google button , if he/she has not signed up before then we can save him to database first and then can show that data and make him/her authenticated on frontend. otherwise if he/ she is already signed up then will fetch previously stored data and make him/her authenticated on frontend.

**Comment by rockingrohit9639** [comment]
> signup and login both can be handled on a single route onclick to any Google button , if he/she has not signed up before then we can save him to database first and then can show that data and make him/her authenticated on frontend. otherwise if he/ she is already signed up then will fetch previously stored data and make him/her authenticated on frontend.

Sounds good, go ahead. You are given 6 days to complete it.
