### ISSUE TITLE
Add horizontal scrollbar on explore categories section

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#184]
On the homepage, Categories Section is responsive but there is not an indicator that shows that we can scroll it horizontally. So, add a horizontal scrollbar or something which indicated to the user that he/she can scroll it.

Something like the image below 👇 
![image](https://user-images.githubusercontent.com/40729749/124344120-43230500-dbee-11eb-9911-d90e028dc8e4.png)

> **Note - Only show scrollbar when is needs to be don't show it on desktop or large screen when all the cards are visible.

**Comment by ghost** [comment]
I would like to work on this issue

**Comment by rockingrohit9639** [comment]
> I would like to work on this issue

Go ahead, you are given 3 days to complete it.
