### ISSUE TITLE
Add some default options on ShowProjects component

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#185]
Add some default options on ShowProjects component something like image below 👇 

![image](https://user-images.githubusercontent.com/40729749/124345173-fa227f00-dbf4-11eb-8968-7ad75ffad165.png)

**Comment by ShwetKhatri2001** [comment]
I would like to work on this issue, I am going to complete my previously assigned issue very soon.

**Comment by kanak22** [comment]
Hey @ShwetKhatri2001 make a PR for the previous issue nd then comment here once, we will assign it to u :)

**Comment by ghost** [comment]
I would like to work on this issue

**Comment by kanak22** [comment]
Hey @Aayushpatil77 , Shwet asked first so this will be assigned to him :) You can look for other issues or create new ones

**Comment by ShwetKhatri2001** [comment]
You can assign now
