### ISSUE TITLE
Make Homepage dynamic by fetching data from db

### ISSUE THREAD

**Issue by naveen8801** [rockingrohit9639/project-zone#189]
## Describe the bug/feature

As of now, our homepage is static i.e we are using hardcoded projects details, I'd like to make it dynamic by fetching all projects from the database and then present them on the homepage.

## Additional context

@kanak22 @rockingrohit9639, as i have made PRs for all my assigned issues so I'd like to work on it, please assign :)

**Comment by kanak22** [comment]
Go Ahead :)
