### ISSUE TITLE
Create a server

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#19]
Create a server in NodeJs in our project to save User data and some other info.

**Comment by mayankmohak** [comment]
i will love work on it

**Comment by rockingrohit9639** [comment]
> i will love work on it

Thank you @mayankmohak bro, I will assign you this issue as soon as you completed the other one.

**Comment by mayankmohak** [comment]
can you please elaborate over the process.

**Comment by rockingrohit9639** [comment]
> can you please elaborate over the process.

Just create a folder named "sercer" in root and all the necessary files in server. Later we will add mongodb and will add all the user data and other infoa into it.

**Comment by rockingrohit9639** [comment]
sorry @mayankmohak bro, I forgot to assign you this issue. Your time will be counted from now. You can let me know if you are having any problems with this issue.

**Comment by rockingrohit9639** [comment]
Hey @mayankmohak bro, I am assigning you this issue now. You can start working on it. Do let me know if you having any problems fixing this issue. You are given 6 days to complete this.

And also please use Express as backend

**Comment by mayankmohak** [comment]
Creating server in root `project-zone` folder will give error due to frontend node module. please mention the which root you were telling about.

> Just create a folder named "sercer" in root and all the necessary files in server. Later we will add mongodb and will add all the user data and other infoa into it.

**Comment by naveen8801** [comment]
Hi @mayankmohak, can you please show us the error you are facing, any screenshot? I have tried to do this locally and there is no issue I found, look at it below,

![Screenshot (84)](https://user-images.githubusercontent.com/54985099/121794751-91189e80-cc28-11eb-8f96-6d6bb26a21b1.png)

Steps I followed:-
- Made a dir named server in the root of project.
- cd server
- npm init
- After providing certain details, the package.json file will appear in server directory.

Hope this will help you.

**Comment by rockingrohit9639** [comment]
> Hi @mayankmohak, can you please show us the error you are facing, any screenshot? I have tried to do this locally and there is no issue I found, look at it below,
> 
> ![Screenshot (84)](https://user-images.githubusercontent.com/54985099/121794751-91189e80-cc28-11eb-8f96-6d6bb26a21b1.png)

yup bro, I told him how to do it.

**Comment by mayankmohak** [comment]
thankyou @naveen8801 and @rockingrohit9639 have made the PR
