### ISSUE TITLE
Make Login and sign up page responsive

### ISSUE THREAD

**Issue by satyampgt4** [rockingrohit9639/project-zone#192]
## Describe the bug/feature

Login and sign up page is not responsive

## To Reproduce

reduce size of browser

## Expected behavior

responsive design

## Environment (please complete the following information):

- Browser: all

## Additional context

screenshot :-
 
![image](https://user-images.githubusercontent.com/59261812/124359513-033a3d00-dc43-11eb-836e-5d8f5c587d47.png) |  
![image](https://user-images.githubusercontent.com/59261812/124359534-1947fd80-dc43-11eb-809d-611027fd7fdf.png)

**Comment by ShwetKhatri2001** [comment]
@rockingrohit9639 I would like to work on this issue

**Comment by satyampgt4** [comment]
@ShwetKhatri2001 You can start working on it
