### ISSUE TITLE
 Create a 404 page 

### ISSUE THREAD

**Issue by satyampgt4** [rockingrohit9639/project-zone#194]
## Describe the bug/feature

Create a 404 page 

## To Reproduce

whenever try to access not existing page

## Expected behavior

show 404 error

## Environment (please complete the following information):

- Browser: all

## Additional context

 Use some image in the 404 page  also  instead of text only

**Comment by rockingrohit9639** [comment]
# Page should match the website theme.

**Comment by naveen8801** [comment]
hi @satyampgt4 @rockingrohit9639, can i work on this, my previous issue is on hold due to some data changes to be made in database :-)

**Comment by rockingrohit9639** [comment]
you can start working on it.
