### ISSUE TITLE
Editing the footer

### ISSUE THREAD

**Issue by NOiR-07** [rockingrohit9639/project-zone#196]
## Describe the bug/feature
In the footer where made with love by open source contributor is written, contributor word looks dim, I will change the word to look alike the rest of them
A clear and concise description of what the bug/feature is.

## To Reproduce

1.Change the position of Contributor word in footer
2.
3.
4.

## Logs

If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):

- OS:
- Browser:

**Comment by kanak22** [comment]
sure :)
