### ISSUE TITLE
Adding server route to save no. of likes  and implementing Like increment on frontend for project

### ISSUE THREAD

**Issue by ShwetKhatri2001** [rockingrohit9639/project-zone#200]
## Describe the bug/feature

Implementing Like increment for a project onclick to like button on project card or project details and 
saving no. of likes for that project  using a server route.

@rockingrohit9639 I 'd like to work on this issue.

**Comment by rockingrohit9639** [comment]
> ## Describe the bug/feature
> Implementing Like increment for a project onclick to like button on project card or project details and
> saving no. of likes for that project using a server route.
> 
> @rockingrohit9639 I 'd like to work on this issue.

You can start working on this issue. You are given 6 days to complete it. 
And make sure only add a like if a user is authenticated and if not show any alert or toast message.
