### ISSUE TITLE
Fix bug on ProjectDetails component

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#201]
![image](https://user-images.githubusercontent.com/40729749/124429164-27a13100-dd8b-11eb-92ed-7ec4b5762f42.png)

In the image above, the share menu is not placed in its right place. The red color shows the wrong place, green color shows the right place. So, fix the position from red to green. And make sure you don't change the styling for Share Menu on Project Componen.

**Comment by ghost** [comment]
@rockingrohit9639 I would like to work on this issue

**Comment by satyampgt4** [comment]
@Aayushpatil77  Go ahead

**Comment by rockingrohit9639** [comment]
@Aayushpatil77 any updates?

**Comment by kanak22** [comment]
@Aayushpatil77 ??

**Comment by anushruti11** [comment]
Can I work on this issue?

**Comment by kanak22** [comment]
Sure
