### ISSUE TITLE
Update preview screenshots in README.md file

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#208]
Update preview screenshots in README.md file

**Comment by RiyaGupta89** [comment]
May I work on this issue?

**Comment by rockingrohit9639** [comment]
> May I work on this issue?

yes, you can work on it. You are given 2 days to do it.

**Comment by rockingrohit9639** [comment]
@RiyaGupta89 any updates?

**Comment by RiyaGupta89** [comment]
@rockingrohit9639 Yes, I have my sem exams going on, I'll do it tomorrow for sure.

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 Yes, I have my sem exams going on, I'll do it tomorrow for sure.

Okay, no problem.
