### ISSUE TITLE
Add a zoom-in on hover effect on projects

### ISSUE THREAD

**Issue by supzi-del** [rockingrohit9639/project-zone#21]
When the project cards are hovered upon, a zoom-in transition can be added for a nice effect and feel.

Please assign this to me under LGM SOC'21.

**Comment by rockingrohit9639** [comment]
> When the project cards are hovered upon, a zoom-in transition can be added for a nice effect and feel.
> 
> Please assign this to me under LGM SOC'21.

Someone has already created the same issue

**Comment by supzi-del** [comment]
Oh okay! If the issue is not solved, you can get back to me :)

**Comment by rockingrohit9639** [comment]
> Oh okay! If the issue is not solved, you can get back to me :)

Yeah sure, Thank you @supzi-del

**Comment by RiyaGupta89** [comment]
There's no zoom in effect on projects? If you want it get done, you can assign me the issue.
