### ISSUE TITLE
Adding pagination on show/search projects page

### ISSUE THREAD

**Issue by ShwetKhatri2001** [rockingrohit9639/project-zone#212]
## Describe the bug/feature

- We can have a pagination having some maximum projects on a page of pagination so that  can avoid long scrolling on a single page.

@rockingrohit9639 I would like to work on this issue

**Comment by rockingrohit9639** [comment]
> ## Describe the bug/feature
> * We can have a pagination having some maximum projects on a page of pagination so that  can avoid long scrolling on a single page.
> 
> @rockingrohit9639 I would like to work on this issue

You can start working on it. You are given 6 days to complete it.
