### ISSUE TITLE
Adding Rating change for project functionality

### ISSUE THREAD

**Issue by ShwetKhatri2001** [rockingrohit9639/project-zone#219]
## Describe the bug/feature

- Project Details can have a functionality to choose rating stars 
- selected rating no. will take part in updating overall average rating for that project 
- New average rating will be updated in database using a server route and that new rating can be shown on project-cards then onwards

@rockingrohit9639 I'd like to work on this issue.

**Comment by rockingrohit9639** [comment]
> ## Describe the bug/feature
> * Project Details can have a functionality to choose rating stars
> * selected rating no. will take part in updating overall average rating for that project
> * New average rating will be updated in database using a server route and that new rating can be shown on project-cards then onwards
> 
> @rockingrohit9639 I'd like to work on this issue.

You can start working on it. You are given 6 days to complete this.
