### ISSUE TITLE
Feature - Share button feature for project card

### ISSUE THREAD

**Issue by naveen8801** [rockingrohit9639/project-zone#23]
## Describe the bug/feature

Adding a feature i.e share button for each project card, with help of that share button one can share a particular project idea to different social platforms like LinkedIn, WhatsApp, Reddit, and many more 

## Expected behavior

A share icon should be present on the project card when the user clicks on it a list of different social platforms will appear, and thus we can share that project idea with others.

**Comment by naveen8801** [comment]
Hi @rockingrohit9639, i'd like to work on it as LGM Soc participant, please assign :))

**Comment by rockingrohit9639** [comment]
> Hi @rockingrohit9639, i'd like to work on it as LGM Soc participant, please assign :))

That's a great idea. I am assigning you this issue. Make sure you complete it in 6 days.

**Comment by naveen8801** [comment]
> > Hi @rockingrohit9639, i'd like to work on it as LGM Soc participant, please assign :))
> 
> That's a great idea. I am assigning you this issue. Make sure you complete it in 6 days.

Thanks @rockingrohit9639 :))

**Comment by naveen8801** [comment]
Hi @rockingrohit9639, i have made a PR, please review :))
