### ISSUE TITLE
Providing Badges based on user activity

### ISSUE THREAD

**Issue by ShwetKhatri2001** [rockingrohit9639/project-zone#230]
## Describe the bug/feature

- Based on user's activity like adding 10,50,100 projects, liking 100 projects, rating 50,100 projects he/she can have some badges . as user keep performing he/she will get new badges. 
- All badges will be saved in database via different routes as user reach required criteria for that badge. 
badges will also be updated on frontend.

@rockingrohit9639 I'd like to work on this issue

**Comment by satyampgt4** [comment]
@ShwetKhatri2001 
Go Ahead;
