### ISSUE TITLE
Saving projects liked and  rated by user

### ISSUE THREAD

**Issue by ShwetKhatri2001** [rockingrohit9639/project-zone#232]
**Describe  feature .**
- saving projects liked by user and projects rated by user in user profile locally and in database
- this can be used to show user whether he/she liked/rated a particular project before or not
- also solving issue will help to give user some badges based on no. of liked / rated projects
- so I want to work on this issue first before solving issue #230

@rockingrohit9639 @satyampgt4 I'd like to work on this issue

**Comment by kanak22** [comment]
Okay :)
