### ISSUE TITLE
FEATURE - Follow a particular user

### ISSUE THREAD

**Issue by naveen8801** [rockingrohit9639/project-zone#236]
**Describe  feature .**

I'd like to add a feature i.e following a particular user which will include:- 
- endpoint on the backend to add a follower to a user
- route on the client-side to fetch a user and see his profile.
-  route on client-side to show all followers of a particular user
- making changes in DB accordingly 

**Additional context**
@rockingrohit9639  @kanak22 , I'd like to work in it , please assign :)

**Comment by kanak22** [comment]
Go ahead

**Comment by rockingrohit9639** [comment]
@naveen8801 any updates on this?

**Comment by ShwetKhatri2001** [comment]
I'd like to work on this issue

**Comment by kanak22** [comment]
Go ahead :)
