### ISSUE TITLE
Adding filter options for Liked, Rated and Added projects

### ISSUE THREAD

**Issue by ShwetKhatri2001** [rockingrohit9639/project-zone#238]
**Describe  feature .**

- User should be able to filter the projects he liked / rated / added  while searching projects for a topic 

 @rockingrohit9639 I would like to work on this issue

**Comment by rockingrohit9639** [comment]
> **Describe feature .**
> 
> * User should be able to filter the projects he liked / rated / added  while searching projects for a topic
> 
> @rockingrohit9639 I would like to work on this issue

Go ahead
