### ISSUE TITLE
Create a landing page

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#24]
## Describe the bug/feature

Create a landing page for the project.
The landing page should be responsive.
Add a title and subtitle.

**Comment by remote007** [comment]
I'd like to work on this issue under label LGMSOC21.

**Comment by rockingrohit9639** [comment]
> I'd like to work on this issue under label LGMSOC21.

I am assigning you this issue. Make sure you complete it in 6 days.

**Comment by ShwetKhatri2001** [comment]
I would like to work on this issue whenever it is possible

**Comment by rockingrohit9639** [comment]
Hey @PadminiRai Remainder !!! This is your last day to submit your code otherwise this issue will be assigned to someone else.

**Comment by rockingrohit9639** [comment]
Hey @ShwetKhatri2001 would you like to work on this issue now?

**Comment by ghost** [comment]
I would like to work on this issue

**Comment by rockingrohit9639** [comment]
> I would like to work on this issue

Bro let me reply first if he don't want to work then I will assign you this

**Comment by ShwetKhatri2001** [comment]
> Hey @ShwetKhatri2001 would you like to work on this issue now?

Yes I would like to work on this issue , You can assign.

**Comment by rockingrohit9639** [comment]
> > Hey @ShwetKhatri2001 would you like to work on this issue now?
> 
> Yes I would like to work on this issue , You can assign.

Okay @ShwetKhatri2001 you can start working on this issue. You are given 6 days to complete this.

**Comment by rockingrohit9639** [comment]
Hey @ShwetKhatri2001 You can reach out to me I have the Figma design ready for the landing page.
