### ISSUE TITLE
Add a navigation bar

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#25]
## Describe the bug/feature

Create a responsive navigation bar.

The menu should include the following nav-links for now

- Home (landing page)
- Find Projects (page for searching the projects)
- Login
- About (keep the link # for now because there is no about us page)
- Contact

It should look something like below ⬇️ 

![image](https://user-images.githubusercontent.com/40729749/122503201-a4a37b00-d015-11eb-85c0-182d76eb3e12.png)

> BG Color : #2D3142
> Text Color: #FFF 
> Icon is in public folder copy it wherever you want. Icon name : icon.png

**Comment by remote007** [comment]
I'd like to work on this issue under label LGMSOC21.

**Comment by Ayushgup85** [comment]
Is this issue still open? If open, can I work on this issue.

**Comment by rockingrohit9639** [comment]
> Is this issue still open? If open, can I work on this issue.

@Ayushgup85 bro, she is working on her other issue whenever she completes another one she will start working on it

**Comment by Ayushgup85** [comment]
> > Is this issue still open? If open, can I work on this issue.
> 
> @Ayushgup85 bro, she is working on her other issue whenever she completes another one she will start working on it

Okk

**Comment by rockingrohit9639** [comment]
hey @Ayushgup85 would you like to work on this issue?

**Comment by ShwetKhatri2001** [comment]
I would like to work on this issue

**Comment by RiyaGupta89** [comment]
Hi sir, I would love to work on this issue. Please assign me this issue.

**Comment by rockingrohit9639** [comment]
> I would like to work on this issue

You can work on this issue. And make it similar to the file I gave you. You are given days to complete it.

**Comment by rockingrohit9639** [comment]
> > I would like to work on this issue
> 
> You can work on this issue. And make it similar to the file I gave you. You are given 6 days to complete it.
