### ISSUE TITLE
✨  Feature : Contact section not working for unregistered user

### ISSUE THREAD

**Issue by kushal98** [rockingrohit9639/project-zone#251]
**Describe  feature .**
The contact form should work despite the user sending request is a registered user or not.
It is not intended that any user who is not a platform user cannot ask questions. 
So it should be allowed

**Additional context**

![image](https://user-images.githubusercontent.com/26721689/125456883-37db28b5-2fa2-4a15-beeb-4013f6837fc2.png)

**Comment by rockingrohit9639** [comment]
> **Describe feature .**
> The contact form should work despite the user sending request is a registered user or not.
> It is not intended that any user who is not a platform user cannot ask questions.
> So it should be allowed
> 
> **Additional context**
> 
> ![image](https://user-images.githubusercontent.com/26721689/125456883-37db28b5-2fa2-4a15-beeb-4013f6837fc2.png)

Thanks for your feature request. We will consider it.
