### ISSUE TITLE
❌   Issue : Validation Missing for empty field

### ISSUE THREAD

**Issue by kushal98** [rockingrohit9639/project-zone#252]
**Issue** 
Validation is missing for message field in case a user sends an empty message in contact section

**Expected Behaviour**
User should be given a prompt to enter some message

**Screenshot**
![image](https://user-images.githubusercontent.com/26721689/125457941-60e56cad-5d1b-4ef9-8ece-8b64dd8f96b3.png)

**Comment by joshi-kaushal** [comment]
Is anyone working on this? If not, please assign it to me...

**Comment by rockingrohit9639** [comment]
> Is anyone working on this? If not, please assign it to me...

you can work on it. Make sure you complete it in 3 days.

**Comment by rockingrohit9639** [comment]
@kushal98 are you working on it?

**Comment by kushal98** [comment]
@rockingrohit9639  It was assigned to @joshi-kaushal so i did not start. Maybe I can do it please assign this to me.

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 It was assigned to @joshi-kaushal so i did not start. Maybe I can do it please assign this to me.

Oh sorry, I thought I assigned you this. You can start working on it. You are given 3 days to complete it .

**Comment by joshi-kaushal** [comment]
Sorry, I had some problems at my side so I couldn't complete it within time.

**Comment by kushal98** [comment]
Hey,
Seems there are some other issues on this as well. Please have a look into the below screenshot 
Even after adding everything it gives the message not sure what is expected out here?

@rockingrohit9639 can you provide more details on what is expected?

![image](https://user-images.githubusercontent.com/26721689/126822814-fcb36f2a-6888-4ed5-9b57-776e3238dc25.png)

**Comment by rockingrohit9639** [comment]
> Hey,
> Seems there are some other issues on this as well. Please have a look into the below screenshot
> Even after adding everything it gives the message not sure what is expected out here?
> 
> @rockingrohit9639 can you provide more details on what is expected?
> 
> ![image](https://user-images.githubusercontent.com/26721689/126822814-fcb36f2a-6888-4ed5-9b57-776e3238dc25.png)

There must be a function to check it, please look for it if you can find it.

**Comment by rockingrohit9639** [comment]
@kushal98 are you working on it?

**Comment by kushal98** [comment]
@rockingrohit9639 the complete requirements is not clear to me like its behaviour with and without login.

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 the complete requirements is not clear to me like its behaviour with and without login.

For now, it is set in a way that only an authenticated user can send the form.
