### ISSUE TITLE
🐛 Bug : Profile component renders authenticated user's content after few seconds

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#254]
**Describe the bug**
There is a bug in the Profile component. When someone is looking at another's profile by using id then the Profile component re-renders after few seconds. 

**Expected behavior**
It should display the details of the userid provided in the URL until the user changes it.

**Screenshots**

![bug](https://user-images.githubusercontent.com/40729749/125621274-6900f6c0-6965-4524-84f4-e3592ce48e3e.gif)

**Comment by ShwetKhatri2001** [comment]
I'd like to work on this issue

**Comment by rockingrohit9639** [comment]
> I'd like to work on this issue

You can start working on it. Make sure you complete it in 4 days.
