### ISSUE TITLE
✨ Feature : Add "press space to focus" in ShowProjects  search component

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#257]
**Describe  feature .**
Add a feature "press space to focus" in ShowProjects's search component. 
Whenever a user press the "space" key, it should focus on the input box.

Also change the placeholder of the input box like the below image - 
![image](https://user-images.githubusercontent.com/40729749/125714000-636758bc-d768-45b3-9430-72b3ed54de7f.png)

**Comment by ShwetKhatri2001** [comment]
I'd like to work on this issue

**Comment by rockingrohit9639** [comment]
> I'd like to work on this issue

you can start working on it.
