### ISSUE TITLE
🐛  Bug : Like functionality not working as expected

### ISSUE THREAD

**Issue by kushal98** [rockingrohit9639/project-zone#259]
**Describe the bug**
When clicking on the like button it likes but again clicking on it should ideally unlike which is not happening

**Expected behaviour**
The click on like button should be a toggle kind of functionality it should perform both like as well as unlike.

**Screenshots**
![image](https://user-images.githubusercontent.com/26721689/125809791-03e9aa65-5044-45ee-86da-8d0330864b49.png)

**Comment by rockingrohit9639** [comment]
> **Describe the bug**
> When clicking on the like button it likes but again clicking on it should ideally unlike which is not happening
> 
> **Expected behaviour**
> The click on like button should be a toggle kind of functionality it should perform both like as well as unlike.
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/26721689/125809791-03e9aa65-5044-45ee-86da-8d0330864b49.png)

it is not implemented yet. you can only like a project for now.
