### ISSUE TITLE
Different colors for different skills

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#26]
Do add some different colors to different skills shown at the bottom of the project card.

**Comment by Hardikpoudel** [comment]
Can i work on this issue as LGMSOC participants?

**Comment by RiyaGupta89** [comment]
May I work on this issue please?

**Comment by rockingrohit9639** [comment]
> May I work on this issue please?

@RiyaGupta89 you can start working on it, make sure you complete it in 6 days.

**Comment by RiyaGupta89** [comment]
Sure, thankyou.

**Comment by RiyaGupta89** [comment]
Hey, you want one particular color for one particular skill or different color and different and same skill?

**Comment by rockingrohit9639** [comment]
> Hey, you want one particular color for one particular skill or different color and different and same skill?

Colors like - 
reactjs - blue
python - yellow etc.

**Comment by RiyaGupta89** [comment]
![color](https://user-images.githubusercontent.com/72425181/121768868-3296e600-cb7e-11eb-94ef-5251ec9864bd.png)
Please check this out, I did like this. But if you don't like it and want me to only use four to five color, basically one color for one language then I'll change it. Let me know.

**Comment by rockingrohit9639** [comment]
> ![color](https://user-images.githubusercontent.com/72425181/121768868-3296e600-cb7e-11eb-94ef-5251ec9864bd.png)
> Please check this out, I did like this. But if you don't like it and want me to only use four to five color, basically one color for one language then I'll change it. Let me know.

I think it will look better if we have particular color for the particular skill

**Comment by RiyaGupta89** [comment]
Yes, I completed that.
