### ISSUE TITLE
🐛 Bug : Comment feature is not working expectedly

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#260]
**Describe the bug**
The comment feature is not working expectedly. Sometimes it adds the comment sometimes it does not, and sometimes the comment is added in the database but not on the frontend.

**Comment by ShwetKhatri2001** [comment]
I'd like to work on this issue .

**Comment by rockingrohit9639** [comment]
> I'd like to work on this issue .

You can start working on this issue. You are given 4 days to complete it.
