### ISSUE TITLE
🐛  Bug : Incorrect redirection after successful login

### ISSUE THREAD

**Issue by kushal98** [rockingrohit9639/project-zone#262]
**Describe the bug**
After doing a successful login into the application, it redirects to the /callback path and gets stuck.

**Expected behaviour**
After the successful login, the application should redirect to the home page.

**Screenshots**
![image](https://user-images.githubusercontent.com/26721689/125957498-6f9c7a90-430d-48f7-9561-a4bf1d44a783.png)

![image](https://user-images.githubusercontent.com/26721689/125957457-b7c55d2f-1721-4e82-8069-cc690e2e891d.png)

**Comment by rockingrohit9639** [comment]
> **Describe the bug**
> After doing a successful login into the application, it redirects to the /callback path and gets stuck.
> 
> **Expected behaviour**
> After the successful login, the application should redirect to the home page.
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/26721689/125957498-6f9c7a90-430d-48f7-9561-a4bf1d44a783.png)
> 
> ![image](https://user-images.githubusercontent.com/26721689/125957457-b7c55d2f-1721-4e82-8069-cc690e2e891d.png)

It was working fine when I did it last time. I will check it and will get back to you.

**Comment by ShwetKhatri2001** [comment]
We can show a loading saying 'Google is logging you in, please wait'
I'd like to work on this issue.

**Comment by rockingrohit9639** [comment]
> We can show a loading saying 'Google is logging you in, please wait'
> I'd like to work on this issue.

Hey @ShwetKhatri2001 can you do this now?

**Comment by ShwetKhatri2001** [comment]
Sure

**Comment by kamal-kaur04** [comment]
Hi @rockingrohit9639 , Can I take up this issue if this is not resolved yet? Thanks.

**Comment by rockingrohit9639** [comment]
> Hi @rockingrohit9639 , Can I take up this issue if this is not resolved yet? Thanks.

Yeah sure @kamal-kaur04

**Comment by kamal-kaur04** [comment]
Hi @rockingrohit9639, I am getting this error while running `npm install` in the /server directory. Any Idea, why?

![image](https://user-images.githubusercontent.com/38219887/139063115-7500e878-4518-4229-adb8-439bce379117.png)
