### ISSUE TITLE
❌  Issue : No Fallback UI for 0 search results on projects

### ISSUE THREAD

**Issue by kushal98** [rockingrohit9639/project-zone#266]
**Description**
In case after search if we don't have any search results a fallback UI should show no results but now I see it keeps showing that "Searching projects for _topic_".

**Expected Result**
It should show a fallback UI with some graphics + text static no matching result found.

**Screenshot**
![image](https://user-images.githubusercontent.com/26721689/126207988-5cc7b421-9bfc-4cd5-9389-c41ab7bd3db2.png)

**Comment by rockingrohit9639** [comment]
> **Description**
> In case after search if we don't have any search results a fallback UI should show no results but now I see it keeps showing that "Searching projects for _topic_".
> 
> **Expected Result**
> It should show a fallback UI with some graphics + text static no matching result found.
> 
> **Screenshot**
> ![image](https://user-images.githubusercontent.com/26721689/126207988-5cc7b421-9bfc-4cd5-9389-c41ab7bd3db2.png)

It will be assigned to you when you completes your other issue.
