### ISSUE TITLE
❌ Issue :  Fix pagination count on ShowProjects components.

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#268]
**Describe the bug**
When a user searches for the projects, the pagination count is more than projects i.e When we click on some pagination count it does not show anything.

**Expected behavior**
There should only be the pagination number in which there are some projects. It should not show the count on which there are no projects. See the screenshot below to see the issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/40729749/126601967-fbf6d825-9163-4f32-a9bb-fc6cd3023f90.png)

**Comment by ShwetKhatri2001** [comment]
I'd like to work on this issue

**Comment by rockingrohit9639** [comment]
> I'd like to work on this issue

go ahead
