### ISSUE TITLE
✨  Enhancement : Fallback UI for featured projects if empty

### ISSUE THREAD

**Issue by kushal98** [rockingrohit9639/project-zone#270]
**Describe  feature .**
Some UI can be shown in case we do not have anything listed on any of the subsection of featured projects in home page.(look into the best android project thing in below screenshot)

**Screenshots**
![image](https://user-images.githubusercontent.com/26721689/126825587-ee282161-ed9d-4b5d-8e33-23481b9e3e1b.png)

**Comment by rockingrohit9639** [comment]
> **Describe feature .**
> Some UI can be shown in case we do not have anything listed on any of the subsection of featured projects in home page.(look into the best android project thing in below screenshot)
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/26721689/126825587-ee282161-ed9d-4b5d-8e33-23481b9e3e1b.png)

i will check it.
