### ISSUE TITLE
✨ Feature : Add "Added by - <Name of user who added the project>" in a Project 

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#271]
**Describe  feature .**
Add an "Added by - <Name>" section in a project both on frontend and backend.
Where <Name> should be the name of the user who added the project. Default added by name should be `Project Zone`

**Comment by ShwetKhatri2001** [comment]
I'd like to work on this issue

**Comment by rockingrohit9639** [comment]
> I'd like to work on this issue

You can start working on it.
