### ISSUE TITLE
✨ Feature: Make project description textarea a rich text editor

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#272]
**Describe  feature .**

Make the description field rich text editor or a WYSIWYG editor. See the image below for reference.

![image](https://user-images.githubusercontent.com/40729749/126855728-da1b4df0-52b2-4f00-83aa-5bbd7ee8c546.png)

### Description textarea should look like this - 
![image](https://user-images.githubusercontent.com/40729749/126855921-8aea024d-d0a6-41cb-ad12-5d6942293e22.png)

**Steps required**
- Make description textarea a rich text in AddNewProject component
- Save the generated HTML in the database
- Show/Render saved HTML on the ProjectDetails component.

`You can use TinyMCE or CKEditor or anything else if you know.`

**Comment by ShwetKhatri2001** [comment]
I'd like to work on this issue

**Comment by rockingrohit9639** [comment]
> I'd like to work on this issue

Okay, I will assign you once you complete the other issue.

**Comment by rockingrohit9639** [comment]
Hi @ShwetKhatri2001, I have assigned you this issue.
