### ISSUE TITLE
Show options while entering somethig in SearchBox

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#276]
**Describe  feature .**
Show options when a user enters something in search-box on ShowProject component. Check image below - 
Also instead of searching $regex in the database, search for the exact match.

* Reach out to me, I will explain more if you have any doubt.
![image](https://user-images.githubusercontent.com/40729749/127604435-36e6f145-001d-46a1-86db-ec6d49dd6fce.png)

**Comment by ShwetKhatri2001** [comment]
I'd like to work on this issue

**Comment by rockingrohit9639** [comment]
> I'd like to work on this issue

you can start working on it.
