### ISSUE TITLE
Add an option to fine the project by skill or name

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#277]
**Describe  feature .**
### Frontend
- Show dropdown to choose to find by name of skill (refer to the image below)

### Backend
- Search for the projects based on the option selected. If skill is selected then search project my skills and if the name is selected then search the projects on the basis of name

**Screenshot**
![image](https://user-images.githubusercontent.com/40729749/127605363-99e08224-6611-4a07-8c27-50729d3f3c66.png)

**Comment by ShwetKhatri2001** [comment]
I'd like to work on this issue.

**Comment by rockingrohit9639** [comment]
> I'd like to work on this issue.

You can start working on it.

**Comment by rockingrohit9639** [comment]
@ShwetKhatri2001 are you working on this one, bro?

**Comment by ShwetKhatri2001** [comment]
Yes, I will complete it by today
