### ISSUE TITLE
Replace all the preview screenshots

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#283]
**Describe Update**
Replace all the preview screenshots with a single GIF image showing all the features.

**Comment by cvsschaitanya** [comment]
May I take up this issue?

**Comment by cvsschaitanya** [comment]
Also one of the screenshots, specifically, the fifth one, is not in the ReadMe file. Is this by design?

**Comment by rockingrohit9639** [comment]
> May I take up this issue?

yeah sure.

> Also one of the screenshots, specifically, the fifth one, is not in the ReadMe file. Is this by design?

Leave all the existing issues, create a single GIF showing all the pages of the project.

**Comment by cvsschaitanya** [comment]
When you say GIF showing all the pages, should I make a GIF with the existing screenshots or I have to create something new?
