### ISSUE TITLE
Add select feature at project level

### ISSUE THREAD

**Issue by Veeresh-Rex** [rockingrohit9639/project-zone#29]
Hey, I am LGMSOC21 participant. I want to change project level input field to select ui.

The Select Option are:-

1. Beginner
2. Intermediate
3. Advanced

@rockingrohit9639  Please assign me this work.

**Comment by rockingrohit9639** [comment]
> Hey, I am LGMSOC21 participant. I want to change project level input field to select ui.
> 
> The Select Option are:-
> 
> 1. Beginner
> 2. Intermediate
> 3. Advanced
> 
> @rockingrohit9639 Please assign me this work.

Ok @Veeresh-Rex you can work on it.
