### ISSUE TITLE
Adding Code of Conduct.md file

### ISSUE THREAD

**Issue by akshatvirmani** [rockingrohit9639/project-zone#31]
## Describe the bug/feature
 To add code of conduct file for contributors.

**Comment by rockingrohit9639** [comment]
> ## Describe the bug/feature
> To add code of conduct file for contributors.

Ok @akshatvirmani I will assign you this issue once you complete the other ones.

**Comment by akshatvirmani** [comment]
Can I work on this issue now?

**Comment by RiyaGupta89** [comment]
May I work on this issue please?

**Comment by rockingrohit9639** [comment]
> Can I work on this issue now?

Yes @akshatvirmani you can work on this issue. Make sure you do it in 3 days.

**Comment by rockingrohit9639** [comment]
> May I work on this issue please?

Sorry, @RiyaGupta89 he asked first. I just forgot to assign him this issue before.
