### ISSUE TITLE
To add CONTRIBUTING_GUIDELINES file.

### ISSUE THREAD

**Issue by hr1shu** [rockingrohit9639/project-zone#33]
## Describe the bug/feature

It'll help newbies like me to get familiar with the basics of contributing factors. I'll be attaching cheat sheets for every stuffs too.

## To Reproduce

1.
2.
3.
4.

## Expected behavior

It'll be a markdown file with clear, concise, and relevant info.

## Logs

If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):

- OS:
- Browser:

**Comment by rockingrohit9639** [comment]
> ## Describe the bug/feature
> It'll help newbies like me to get familiar with the basics of contributing factors. I'll be attaching cheat sheets for every stuffs too.
> 
> ## To Reproduce
> Steps to reproduce the behavior:
> 
> 
> ## Expected behavior
> It'll be a markdown file with clear, concise, and relevant info.
> 
> ## Logs
> If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).
> 
> ## Environment (please complete the following information):
> * OS:
> * Browser:
> 
> ## Additional context
> Add any other context about the problem here.

It would be very helpful. I am assigning you this issue. Make sure you complete it in 4 days.

**Comment by hr1shu** [comment]
Thanks a lot.
On it boss!!
