### ISSUE TITLE
storing login/signup userdata to reducerstate by dispatching actions

### ISSUE THREAD

**Issue by ShwetKhatri2001** [rockingrohit9639/project-zone#34]
I am working on issue #6.

I would also like to handle states for login and signup pages and store userdata to reducer state by dispatching actions.
So that we can have currently logged in user's data at root level , who signed up / logged in using email.

Assign this issue @rockingrohit9639 . I will be contributing under LGM-SOC.

**Comment by rockingrohit9639** [comment]
> I am working on issue #6.
> 
> I would also like to handle states for login and signup pages and store userdata to reducer state by dispatching actions.
> So that we can have currently logged in user's data at root level , who signed up / logged in using email.
> 
> Assign this issue @rockingrohit9639 . I will be contributing under LGM-SOC.

Hi @ShwetKhatri2001 you can work on this issue but make sure you make different pull requests for different issues. Don't merge the code of two issues into one. Whenever you complete previous issue I will assign you with this one.

**Comment by ShwetKhatri2001** [comment]
Sure, I will make a PR for issue #6 first.

**Comment by ShwetKhatri2001** [comment]
@rockingrohit9639 I would like to work on this issue now, my PR for issue #6 has been merged, you can assign.

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 I would like to work on this issue now, my PR for issue #6 has been merged, you can assign.

Hey @ShwetKhatri2001 bro, You can start working on this issue now. You are given 4 days to complete this.
