### ISSUE TITLE
Add chips in project skills

### ISSUE THREAD

**Issue by Veeresh-Rex** [rockingrohit9639/project-zone#39]
Hey, I am LGM-SOC21 participant.

### What i want to change

- I want to add chips to project skill while adding new project.
- Chips data contains some famous Tech and user can select that chips if their Tech meets.
- Not mention tech can be also add using chip input.

@rockingrohit9639  I'd love to work on it.

**Comment by rockingrohit9639** [comment]
> Hey, I am LGM-SOC21 participant.
> 
> ### What i want to change
> * I want to add chips to project skill while adding new project.
> * Chips data contains some famous Tech and user can select that chips if their Tech meets.
> * Not mention tech can be also add using chip input.
> 
> @rockingrohit9639 I'd love to work on it.

Hey @Veeresh-Rex I have assigned you this issue. Make sure you complete it in 5 days.
