### ISSUE TITLE
Documentation - Add MIT license 

### ISSUE THREAD

**Issue by naveen8801** [rockingrohit9639/project-zone#42]
## Describe the bug/feature

Public repositories on GitHub are often used to share open-source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software. Therefore adding a MIT license is good option for this project.

## Expected behavior

Add a LICENSE file in root of project repo

## Additional context

Read more about licenses here https://choosealicense.com/

**Comment by mayankmohak** [comment]
i want to work on this. LGMSOC21

**Comment by rockingrohit9639** [comment]
> ## Describe the bug/feature
> Public repositories on GitHub are often used to share open-source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software. Therefore adding a MIT license is good option for this project.
> 
> ## Expected behavior
> Add a LICENSE file in root of project repo
> 
> ## Additional context
> Read more about licenses here https://choosealicense.com/

I have assigned you this issue. You can go ahead and add the LICENSE file.

**Comment by naveen8801** [comment]
Hey @rockingrohit9639 please assign this one to @mayankmohak, I am looking upon #41

**Comment by rockingrohit9639** [comment]
> Hey @rockingrohit9639 please assign this one to @mayankmohak, I am looking upon #41

Ohh great. I am assigning this issue to @mayankmohak 

Hey @mayankmohak you can work on this issue now. Make sure you complete it in 3 days.
