### ISSUE TITLE
Documentation - Add Badges in readme

### ISSUE THREAD

**Issue by naveen8801** [rockingrohit9639/project-zone#48]
## Describe the bug/feature

Add the following badges in the readme file on top:
- Issue count
- Star count
- Fork count
- License
- Slack channel link

on click, these badges should open respective pages

## Additional context

shields.io can be used for generating the badges.

**Comment by RiyaGupta89** [comment]
I can add badges in the readme.md file. Please assign me this issue under LGMSOC'21.

**Comment by rockingrohit9639** [comment]
> ## Describe the bug/feature
> Add the following badges in the readme file on top:
> 
> * Issue count
> * Star count
> * Fork count
> * License
> * Slack channel link
> 
> on click, these badges should open respective pages
> 
> ## Additional context
> shields.io can be used for generating the badges.

hey @naveen8801 bro, you can start working on this issue. Make sure you fix this in 4 days.
