### ISSUE TITLE
Enhancing Readme file

### ISSUE THREAD

**Issue by akshatvirmani** [rockingrohit9639/project-zone#5]
I would like to work on this issue. Kindly assign this to me under LGM SOC.

**Comment by rockingrohit9639** [comment]
> I would like to work on this issue. Kindly assign this to me under LGM SOC.

Hey @akshatvirmani 
You can surely work on it. But I would like to let you know that your PRs before the 10th of June will not be counted.

**Comment by akshatvirmani** [comment]
Okay

**Comment by rockingrohit9639** [comment]
Hey @akshatvirmani Now, you can start working on this issue. Make sure you complete it in 3 days.

**Comment by sudeepshukla930** [comment]
Hey @rockingrohit9639 ,
Can i update readme for this project ??

**Comment by rockingrohit9639** [comment]
> Hey @rockingrohit9639 ,
> Can i update readme for this project ??

yes, sure
