### ISSUE TITLE
Limit description of projects

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#50]
Limit the description of the project card to come specific word count. After some specific word count add ... at the end.

**Comment by naveen8801** [comment]
@rockingrohit9639  I'd like to work on it, please assign :-))

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 I'd like to work on it, please assign :-))

You can start working on this issue. Make sure you complete it in 4 days.

**Comment by naveen8801** [comment]
@rockingrohit9639  Should I put a limit upto 50 characters?

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 Should I put a limit upto 50 characters?

Totally up to you. It should look fine.

**Comment by naveen8801** [comment]
> > @rockingrohit9639 Should I put a limit upto 50 characters?
> 
> Totally up to you. It should look fine.

okay @rockingrohit9639 👍

**Comment by naveen8801** [comment]
hi @rockingrohit9639, i have made a PR, please review 😃
