### ISSUE TITLE
Add separate page to see full project

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#52]
Add a separate page to view the full project and a "Read More" button on the project cards.
When a user clicks on the "Read More" button it should navigate to a new page and show all the details and full description of the project.

**Comment by naveen8801** [comment]
@rockingrohit9639  I'd like to work on it, please elaborate about details which should be present on a particular project page :-))

**Comment by ghost** [comment]
I would like to work on this issue
