### ISSUE TITLE
A bug after changing search query

### ISSUE THREAD

**Issue by Veeresh-Rex** [rockingrohit9639/project-zone#59]
## Describe the bug/feature
After searching a project, if I click  'let us decide a project for you'. I shows a random project for me. and if again I change the search query, the the previous result doesn't remove.

## Expected behavior

Whenever user change the search query , the previous 'let us decide a project for you' result should be remove

**Comment by Veeresh-Rex** [comment]
Hey @rockingrohit9639  I want to work on this issue as a LGMSOC21 participant.

**Comment by rockingrohit9639** [comment]
> Hey @rockingrohit9639 I want to work on this issue as a LGMSOC21 participant.

Hey @Veeresh-Rex Thank you for finding a bug in our project. I have assigned you this issue. You are given 3 days to resolve this.
