### ISSUE TITLE
Proper Folder Structure for Backend

### ISSUE THREAD

**Issue by naveen8801** [rockingrohit9639/project-zone#61]
## Describe the bug/feature

Make proper folder structure for backend (server dir.) similar to the screenshot below:

## Expected behavior

![folder strucutre](https://user-images.githubusercontent.com/54985099/121795839-f8871c00-cc31-11eb-82dd-25bdb1351ed2.gif)

@rockingrohit9639, I'd like to work on it, please assign :-)

**Comment by rockingrohit9639** [comment]
> ## Describe the bug/feature
> Make proper folder structure for backend (server dir.) similar to the screenshot below:
> 
> ## Expected behavior
> ![folder strucutre](https://user-images.githubusercontent.com/54985099/121795839-f8871c00-cc31-11eb-82dd-25bdb1351ed2.gif)
> 
> @rockingrohit9639, I'd like to work on it, please assign :-)

you can work on it
