### ISSUE TITLE
Add authentication

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#63]
## Feature

Add authentication in our app for login user and signup user.

For /signup - add user's email and password in db and do necessary stuff

For /login - verify user's email and password and return necessary user's data

Contact me for db uri and othrr details

**Comment by naveen8801** [comment]
Hi @rockingrohit9639, I'd like to work on it, please assign 😃

**Comment by rockingrohit9639** [comment]
> Hi @rockingrohit9639, I'd like to work on it, please assign 😃

Hey @naveen8801 you can start working on this issue.

**Comment by medhir23** [comment]
Hi @rockingrohit9639, can i please work on this?

**Comment by rockingrohit9639** [comment]
> Hi @rockingrohit9639, can i please work on this?

@Shady2320 someone is already working on it

**Comment by rockingrohit9639** [comment]
> > Hi @rockingrohit9639, I'd like to work on it, please assign 😃
> 
> Hey @naveen8801 you can start working on this issue.
