### ISSUE TITLE
Making trending projects section responsive

### ISSUE THREAD

**Issue by pallavi-1812** [rockingrohit9639/project-zone#66]
## Describe the bug/feature

The section about trending projects is not responsive. I would like to make it responsive on small screens. Please assign me this issue
![Annotation 2021-06-14 164716](https://user-images.githubusercontent.com/67572675/121884398-7cbfc900-cd30-11eb-8388-205a7c1e0079.png)

**Comment by kanak22** [comment]
Go Ahead :) Make sure to complete it in 5 days.
