### ISSUE TITLE
Add Code of conduct, contribution guidelines and license in readme file.

### ISSUE THREAD

**Issue by Shaishav0507** [rockingrohit9639/project-zone#68]
## Describe the bug/feature

Hey @rockingrohit9639 
I would like to add code of conduct, license and contribution guidelines in readme file.
As they are present in branch but not linked in readme file.
Please assign it to me.
Thanks

## To Reproduce

1.
2.
3.
4.

## Logs

If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):

- OS:
- Browser:

**Comment by kanak22** [comment]
Go ahead  :)
