### ISSUE TITLE
Design a logo for Project Zone

### ISSUE THREAD

**Issue by supzi-del** [rockingrohit9639/project-zone#71]
## Describe the bug/feature

I want to design a logo to add in the nav bar near the title Project Zone.

## Environment (please complete the following information):

- OS:
- Browser:

**Comment by kanak22** [comment]
@supzi-del  Go ahead :)

**Comment by supzi-del** [comment]
Designed these two! Please have a look. I can work on other designs too.

![P](https://user-images.githubusercontent.com/78655439/122232930-42456000-ced9-11eb-923a-523fce332b55.png)
![P (1)](https://user-images.githubusercontent.com/78655439/122232948-483b4100-ced9-11eb-9c13-8faefab21175.png)

**Comment by rockingrohit9639** [comment]
> Designed these two! Please have a look. I can work on other designs too.
> 
> ![P](https://user-images.githubusercontent.com/78655439/122232930-42456000-ced9-11eb-923a-523fce332b55.png)
> ![P (1)](https://user-images.githubusercontent.com/78655439/122232948-483b4100-ced9-11eb-9c13-8faefab21175.png)

@kanak22 have a look

**Comment by kanak22** [comment]
Both are good but I will suggest the first one as it goes well with the theme of the project.

**Comment by supzi-del** [comment]
How can I add the logo to the page? Like there's no HTML code for that in the project files.

**Comment by supzi-del** [comment]
Also should the background color be transparent?

**Comment by rockingrohit9639** [comment]
> Also should the background color be transparent?

Just add the logo file to the project and push the changes. And yeah it would be great if you can give both a transparent and a jpeg file.

**Comment by supzi-del** [comment]
> > Also should the background color be transparent?
> 
> Just add the logo file to the project and push the changes. And yeah it would be great if you can give both a transparent and a jpeg file.

Like, 2 files? - 1 transparent(png) and 1 jpg(white bg)

**Comment by rockingrohit9639** [comment]
> > > Also should the background color be transparent?
> > 
> > 
> > Just add the logo file to the project and push the changes. And yeah it would be great if you can give both a transparent and a jpeg file.
> 
> Like, 2 files? - 1 transparent(png) and 1 jpg(white bg)

Yes
