### ISSUE TITLE
Change Project Card style

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#72]
Change the styling of the Project Card to something below

![image](https://user-images.githubusercontent.com/40729749/122158819-e05e0980-ce8a-11eb-90f6-dd2e77ec6767.png)

**Comment by WebVishal** [comment]
please assign me I want to work under LGMSOC'21 as a participant

**Comment by rockingrohit9639** [comment]
> please assign me I want to work under LGMSOC'21 as a participant

You can start working on this issue. You are given 6 days to complete this.

**Comment by rockingrohit9639** [comment]
@WebVishal bro, are you working on it?

**Comment by rockingrohit9639** [comment]
Hey @WebVishal, This is your last day to submit your PR.

**Comment by rockingrohit9639** [comment]
Hey @ShwetKhatri2001 wiuld you like to work on this issue?

**Comment by ShwetKhatri2001** [comment]
Sure, You can assign

**Comment by rockingrohit9639** [comment]
> Sure, You can assign

Okay, I will assign you once you complete the other one.

**Comment by RituCs** [comment]
I would like to work on this issue under LGMSOC'21.Please assign it to me.

**Comment by ShwetKhatri2001** [comment]
> > Sure, You can assign
> 
> Okay, I will assign you once you complete the other one.

You can assign this issue now, I have completed my other issues.

**Comment by rockingrohit9639** [comment]
> > > Sure, You can assign
> > 
> > 
> > Okay, I will assign you once you complete the other one.
> 
> You can assign this issue now, I have completed my other issues.

Go Ahead. You are given 6 days to complete this.
