### ISSUE TITLE
Adding more project ideas in JavaScript & MERN Stack and Trending Section

### ISSUE THREAD

**Issue by WebVishal** [rockingrohit9639/project-zone#73]
hi, I'm Vishal, I want to contribute to this project  I looking at this project after that I Realised we should need some more project adding regarding JavaScript & React  like AgeCalculator, Sanke Game, Battery Level, CaptchaValidator, etc 

If you like this idea then please assign me, I want to contribute as a participant of LGMSOC'21

**Comment by kanak22** [comment]
So how many projects do u want to add? like specify them nd their names
