### ISSUE TITLE
Change style of ProjectDetailsCard

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#74]
Chnage styles of ProjectDetailsCard to the following styles - ⬇️

![image](https://user-images.githubusercontent.com/40729749/122163447-d6d89f80-ce92-11eb-90a4-a8ad0985dd4c.png)

**Comment by ghost** [comment]
I would like to work on this issue

**Comment by rockingrohit9639** [comment]
> I would like to work on this issue

you can start working on this issue. Make sure you complete it in 5 days.
