### ISSUE TITLE
Change footer style

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#75]
Change the style of the footer as shown in the following image ⬇️ 

![image](https://user-images.githubusercontent.com/40729749/122163688-32a32880-ce93-11eb-9ff3-5a9f5fa93c93.png)

**Comment by ghost** [comment]
I would like to work on this issue

**Comment by rockingrohit9639** [comment]
> I would like to work on this issue

Will assign you when you complete the other one.

**Comment by ShwetKhatri2001** [comment]
I would like to work on this issue

**Comment by Kumud-869231165** [comment]
I would like to work on this issue as a LGM-SOC participant. I have designed footers

**Comment by rockingrohit9639** [comment]
> I would like to work on this issue as a LGM-SOC participant. I have designed footers

Hey @Kumud-869231165 someone is already assigned to this issue.
