### ISSUE TITLE
Add LGM-SOC'21 score card in readme.md

### ISSUE THREAD

**Issue by ishitakapoor26** [rockingrohit9639/project-zone#78]
Add LGM-SOC'21 score card in readme.md

**Comment by ishitakapoor26** [comment]
@rockingrohit9639 pls assign this issue to me.

**Comment by kanak22** [comment]
@ishitakapoor26 firstly complete all the issues assigned to u then we will assign this one to you :)

**Comment by ishitakapoor26** [comment]
> @ishitakapoor26 firstly complete all the issues assigned to u then we will assign this one to you :)

@kanak22 okay pls check I've raised pr for other issues.

**Comment by rockingrohit9639** [comment]
@ishitakapoor26 you can start working on it. You are given 2 days to complete it.

**Comment by kanak22** [comment]
> > @ishitakapoor26 firstly complete all the issues assigned to u then we will assign this one to you :)
> 
> @kanak22 okay pls check I've raised pr for other issues.

yep i saw :)
