### ISSUE TITLE
Changes style of cards 

### ISSUE THREAD

**Issue by SamikshaSankar** [rockingrohit9639/project-zone#8]
Making zoom on hover 

I work on this issue under LGM-SOC'21 participant..please assigned me @rockingrohit9639

**Comment by rockingrohit9639** [comment]
Hey, @SamikshaSankar I have assigned you this issue. You are given 3 days to complete this issue.

**Comment by Deepak735** [comment]
i want to work on this issue as an LGMSOC participant. Plz assign it to me

**Comment by SamikshaSankar** [comment]
@rockingrohit9639 is it ok?
![d](https://user-images.githubusercontent.com/52104082/121785533-e2e50880-cbd7-11eb-83c6-1e9346a17173.jpeg)

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 is it ok?
> ![d](https://user-images.githubusercontent.com/52104082/121785533-e2e50880-cbd7-11eb-83c6-1e9346a17173.jpeg)

Styling is totally up to you. But make sure you pull all the changes from upstream before creating the PR otherwise it will lead to some issues.
