### ISSUE TITLE
Create About us page

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#80]
Create an About page and also show the name and details of all the contributors on that page and a little bit about our project.

**Comment by rockingrohit9639** [comment]
hey @Aayushpatil77 would you like to work on this issue?

**Comment by ghost** [comment]
Yes, I would like to work on this issue

**Comment by rockingrohit9639** [comment]
> Yes, I would like to work on this issue

Okay you can start, you are given 6 days to complete this.

**Comment by rockingrohit9639** [comment]
@RiyaGupta89 would you like to work on this issue?

**Comment by RiyaGupta89** [comment]
> @RiyaGupta89 would you like to work on this issue?

Yes, I would like to work on this issue.

**Comment by RiyaGupta89** [comment]
If you have some demo UI of the page, you can show me. Otherwise I'll figure it out.

**Comment by rockingrohit9639** [comment]
> If you have some demo UI of the page, you can show me. Otherwise I'll figure it out.

I do not have the UI yet. You can use your imagination.

**Comment by rockingrohit9639** [comment]
@RiyaGupta89 I have assigned you and you are given 6 days to complete  this

**Comment by RiyaGupta89** [comment]
> @RiyaGupta89 I have assigned you and you are given 6 days to complete this

Sure, I'll complete the work in the given time.

**Comment by RiyaGupta89** [comment]
@rockingrohit9639 Do I need to add the image of the contributors? If not then what are the details that should be present on the page about the contributors?

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 Do I need to add the image of the contributors? If not then what are the details that should be present on the page about the contributors?

You can get all the details of the contributors using GitHub API. Username and their profile image should be there on the about us page.

**Comment by rockingrohit9639** [comment]
Hey, @RiyaGupta89 If you are having any difficulties in doing it then you can contact me I can help you out.

**Comment by RiyaGupta89** [comment]
Yes @rockingrohit9639, I just want to know from where to get the github API. Then I will fetch and display the details on the about us page.

**Comment by rockingrohit9639** [comment]
> Yes @rockingrohit9639, I just want to know from where to get the github API. Then I will fetch and display the details on the about us page.

Make get request to this endpoint - 
https://api.github.com/repos/rockingrohit9639/project-zone/contributors

**Comment by RiyaGupta89** [comment]
https://user-images.githubusercontent.com/72425181/123535730-4ed08080-d743-11eb-8589-0c0b003aa118.mp4

Have a look, does it look okay?

**Comment by rockingrohit9639** [comment]
>  bandicam.2021-06-27.12-25-35-435_Trim_Trim.mp4 
> Have a look, does it look okay?

This is looking awesome.

**Comment by RiyaGupta89** [comment]
@rockingrohit9639 Thankyou! Should I make PR then?

**Comment by RiyaGupta89** [comment]
@rockingrohit9639 I'm not able to make the page responsive. 
![unresponsive](https://user-images.githubusercontent.com/72425181/123536696-8e01d000-d749-11eb-94fa-ef684b0d6e03.png)
In the right side of the page which I marked with red color, I don't know why that extra space is left out. Its because of navbar or something or idk. I tried making the page responsive, its not that difficult too but because of that extra space present. I am not able to do it. I also don't know how to resolve it.

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 I'm not able to make the page responsive.
> ![unresponsive](https://user-images.githubusercontent.com/72425181/123536696-8e01d000-d749-11eb-94fa-ef684b0d6e03.png)
> In the right side of the page which I marked with red color, I don't know why that extra space is left out. Its because of navbar or something or idk. I tried making the page responsive, its not that difficult too but because of that extra space present. I am not able to do it. I also don't know how to resolve it.

Okay, No problem

**Comment by RiyaGupta89** [comment]
@rockingrohit9639 Should I make PR or not?

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 Should I make PR or not?

Make it
