### ISSUE TITLE
Add Contact us page

### ISSUE THREAD

**Issue by Shaishav0507** [rockingrohit9639/project-zone#83]
## Describe the bug/feature

Hey @rockingrohit9639 
I would like to add contact us page .
Please assign it to me.
Thanks

## To Reproduce

1.
2.
3.
4.

## Logs

If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):

- OS:
- Browser:

**Comment by rockingrohit9639** [comment]
Hey, @Shaishav0507 You can start working on this issue. Make sure you complete it in 6 days.
