### ISSUE TITLE
Make the badges of single type and add some more

### ISSUE THREAD

**Issue by Umesh-01** [rockingrohit9639/project-zone#85]
## Describe the bug/feature

In README.md file- Make the existing badges of single type because they are not looking good and add some more badges to the top of readme.md file, since the badges will be colorful and more attractive at the top of README.md file than the text the users will like it and it will also help them to navigate to different sections/ webpages like PRs, issues, contributors, etc.

![image](https://user-images.githubusercontent.com/83420185/122446903-ccb4bf00-cfc0-11eb-9f55-f79004103b92.png)

## To Reproduce

1. I will make all the badges of same type.
2. I will add some more badges.
3. I will add links to these badges so that the user can navigate to the related section/webpage.
4. I will align all them to the center.

## Expected behavior

I will add some more badges and make the existing badges of single type so that the README.md file will look more attractive and awesome. And also I will align them all to the center.

## Environment (please complete the following information):

- OS: Windows
- Browser: Chrome

**Comment by Umesh-01** [comment]
@rockingrohit9639 Should I make these changes??

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 Should I make these changes??

You can start working on it. You are given 3 days to complete this.
