### ISSUE TITLE
Add category section on homepage

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#87]
Add a category section on the homepage.
This should look like - 🔽 

![image](https://user-images.githubusercontent.com/40729749/122508058-f69cce80-d01e-11eb-90c9-96dd4708ded2.png)

Ask me if you need any help.

**Comment by Veeresh-Rex** [comment]
hey @rockingrohit9639  I'd like to work on this issue.

**Comment by kanak22** [comment]
Go ahead :) make sure to complete this within 6 days
