### ISSUE TITLE
Trigger Button 

### ISSUE THREAD

**Issue by SamikshaSankar** [rockingrohit9639/project-zone#9]
Click on Enter Key Press in search bar

Please assign @rockingrohit9639

**Comment by rockingrohit9639** [comment]
> Click on Enter Key Press in search bar
> 
> Please assign @rockingrohit9639

Ok @SamikshaSankar I will assign you as soon as the program starts.

**Comment by rockingrohit9639** [comment]
Hey, @SamikshaSankar you can start working on this issue now. Make sure you complete this issue in 5 days.

**Comment by rockingrohit9639** [comment]
Hey @SamikshaSankar are you working on it?

**Comment by SamikshaSankar** [comment]
Yes...but search bar is not working..I guess bcz whenever I search something on it..not show anything
TypeError: projects is undefined shows like this

**Comment by rockingrohit9639** [comment]
> Yes...but search bar is not working..I guess bcz whenever I search something on it..not show anything
> TypeError: projects is undefined shows like this

Have you pulled all the current code?

**Comment by rockingrohit9639** [comment]
@SamikshaSankar hi, is there any problem you are not able to make PR?

**Comment by SamikshaSankar** [comment]
Yes... Please assigned next issue...I will be worked later on this issue

**Comment by rockingrohit9639** [comment]
@SamikshaSankar are you workong on it?
