### ISSUE TITLE
Change Contact Us page style

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#92]
Change the style of the Contact Us page like below - 🔽 

![image](https://user-images.githubusercontent.com/40729749/122640443-3cd85780-d11d-11eb-80e3-b413b47ba3da.png)

Reach out to me for images and other resources

**Comment by Shaishav0507** [comment]
@rockingrohit9639 Can I work on this ?

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 Can I work on this ?

You can start working on this issue. Make sure you do the styling given in the image above. To get the images you can reach out to me on Discord or Slack. You are given 5 days to complete it.

**Comment by Shaishav0507** [comment]
Ok sure @rockingrohit9639
