### ISSUE TITLE
Show trending projects on separate page

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#93]
Create a page to show TrendingProjects and remove TrendingProjects from Home.

**Comment by RiyaGupta89** [comment]
I can do it. Please assign this issue to me. UI will be similar to the home page, right?

**Comment by anushruti11** [comment]
@rockingrohit9639 If anyone is not working on this, I would like to work on this issue.

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 If anyone is not working on this, I would like to work on this issue.

She has two other issue to fix, so think you can work on it. You are given 4 days to complete it. You can react out to me if you have any issue while doing it.

**Comment by anushruti11** [comment]
> > @rockingrohit9639 If anyone is not working on this, I would like to work on this issue.
> 
> She has two other issue to fix, so think you can work on it. You are given 4 days to complete it. You can react out to me if you have any issue while doing it.

@rockingrohit9639 Should I add it in the navbar section?

**Comment by rockingrohit9639** [comment]
> > > @rockingrohit9639 If anyone is not working on this, I would like to work on this issue.
> > 
> > 
> > She has two other issue to fix, so think you can work on it. You are given 4 days to complete it. You can react out to me if you have any issue while doing it.
> 
> @rockingrohit9639 Should I add it in the navbar section?

You have to create a new component and they show TrendingPrjoject component there.
