### ISSUE TITLE
Fix Footer on Home Page

### ISSUE THREAD

**Issue by Shaishav0507** [rockingrohit9639/project-zone#94]
## Describe the bug/feature

Footer is not there on the home.
Please assign it to me.
Thanks

## To Reproduce

1.
2.
3.
4.

## Logs

If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):

- OS:
- Browser:

**Comment by rockingrohit9639** [comment]
> ## Describe the bug/feature
> Footer is not there on the home.
> Please assign it to me.
> Thanks
> 
> ## To Reproduce
> Steps to reproduce the behavior:
> 
> 
> ## Expected behavior
> A clear and concise description of what you expected to happen.
> 
> ## Logs
> If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).
> 
> ## Environment (please complete the following information):
> * OS:
> * Browser:
> 
> ## Additional context
> Add any other context about the problem here.

Footer is already there on every page. You might not have pulled all the changes.

**Comment by Shaishav0507** [comment]
I checked from the live server live present there in the description.
Please update that link.

**Comment by rockingrohit9639** [comment]
> ption.
> Please update that link.

Do you mean on netlify?

**Comment by Shaishav0507** [comment]
> > ption.
> > Please update that link.
> 
> Do you mean on netlify?

Yes

**Comment by rockingrohit9639** [comment]
> > > ption.
> > > Please update that link.
> > 
> > 
> > Do you mean on netlify?
> 
> Yes

It is not updated yet. You can run the project locally to see all the changes.

**Comment by rockingrohit9639** [comment]
I am closing this issue.
