### ISSUE TITLE
Add project logo icon in Footer

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#95]
Add project logo icon in the footer as shown in the image below ⬇️ 

![image](https://user-images.githubusercontent.com/40729749/122640981-0a7c2980-d120-11eb-9781-e6cc21fd9129.png)

**Comment by rockingrohit9639** [comment]
Hey, @RiyaGupta89 would you like to work on this issue?

**Comment by RiyaGupta89** [comment]
@rockingrohit9639 Yes sure sir.

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 Yes sure sir.

Okay, you can start working on this issue. You are given 4 days to complete it. 
And yeah, don't call me sir 😃

**Comment by RiyaGupta89** [comment]
![2](https://user-images.githubusercontent.com/72425181/122643969-4dde9400-d130-11eb-84e4-c93cd1449275.png)
Please have a look, is this okay? Should I request for PR?

**Comment by RiyaGupta89** [comment]
Where will I get the logo image with transparent background? I have the logo but that has white background.

**Comment by RiyaGupta89** [comment]
![3](https://user-images.githubusercontent.com/72425181/122645716-58e9f200-d139-11eb-9901-bbbca43af262.png)
Have a look, it looks quite bad with this image.

**Comment by rockingrohit9639** [comment]
> ![3](https://user-images.githubusercontent.com/72425181/122645716-58e9f200-d139-11eb-9901-bbbca43af262.png)
> Have a look, it looks quite bad with this image.

Use icon.png file in public folder

**Comment by RiyaGupta89** [comment]
![8](https://user-images.githubusercontent.com/72425181/122647247-e54be300-d140-11eb-8e93-676f5d6a29a2.png)
Done. Please review the code.
