### ISSUE TITLE
Add images for each steps in README.md file

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#96]
Add images for each step like Fork, Clone, etc.

**Comment by RiyaGupta89** [comment]
I can do it. Please assign this issue to me.

**Comment by rockingrohit9639** [comment]
> I can do it. Please assign this issue to me.

You are already assigned to an issue. Please fix that issue first and then ask for another issue. I will assign you once you complete the other issue,

**Comment by rockingrohit9639** [comment]
@RiyaGupta89 you can work on it now.
