### ISSUE TITLE
Change screenshots in README.md file

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/project-zone#97]
Change the preview screenshots present in the README file with the new screenshots.

**Comment by RiyaGupta89** [comment]
Can you elaborate more?

**Comment by kanak22** [comment]
it is about changing the present ss of the project preview in readme i.e which shows how the project looks like, as recently the project was updated in terms of how it looks. I hope u got it @RiyaGupta89 :)

**Comment by ghost** [comment]
Can i work on this?

**Comment by kanak22** [comment]
sue @Devtinator  Go Ahead :)
